### ISSUE TITLE
nginx not built with PIE

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/staticfile-buildpack#106]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf250 cli6.28

What version of the buildpack you are using?
1.4.9

If you were attempting to accomplish a task, what was it you were attempting to do?
N/A

What did you expect to happen?
nginx in the buildpack should be built as PIE (as well as other hardening features, if available)

What was the actual behavior?
nginx is not built as PIE
```
$ hardening-check ./nginx # ./nginx was extracted from a running container
./nginx:
 Position Independent Executable: no, normal executable!
 Stack protected: yes
 Fortify Source functions: yes (some protected functions found)
 Read-only relocations: yes
 Immediate binding: no, not found!
```

see https://wiki.debian.org/Hardening and specifically https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/vivid/nginx/vivid/view/head:/debian/rules

**Comment by sclevine** [comment]
Hi @CAFxX,

Thanks for the report. It does appear that we can enable PIE and `BIND_NOW` without impacting performance on 64-bit systems.

I'll prioritize this change for both the staticfile and php buildpacks.

**Comment by CAFxX** [comment]
yup, I haven't had time to confirm yet but I guess this may apply to many of the packages in the buildpacks since, unfortunately, it's not on by default

**Comment by sclevine** [comment]
Sorry for the delay in getting these changes out. NGINX is built as a PIE with immediate binding on the develop branch of both the staticfile and PHP buildpacks. The change will be present in the next release of each buildpack.
