### ISSUE TITLE
Include ngx_pagespeed (take #2)

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/staticfile-buildpack#107]
(this is a repost of #79, that was closed pending stabilization of the dynamic module system)

What version of Cloud Foundry are you using?
250

What version of the buildpack you are using?
1.4.9

If you were attempting to accomplish a task, what was it you were attempting to do?
Enable pagespeed via custom nginx.conf

What did you expect to happen?
The pagespeed module to start processing requests

What was the actual behavior?
ngx_pagespeed is not included in the nginx package, so nginx fails because of unknown configuration directive.

We briefly discussed the purpose of pagespeed over https://cloudfoundry.slack.com/archives/buildpacks/p1468242176000666 and decided to file a ticket.

The original ticket was closed because the dynamic module system was not deemed mature enough. Please note that **whether to include the module as dynamic or static is orthogonal to this story**. It can be included as static for now, and then converted to dynamic later (if needed).

The dynamic module system has matured since then: https://www.nginx.com/blog/compiling-dynamic-modules-nginx-plus/

ngx_pagespeed now has documentation explaining how to build it as a dynamic module: https://modpagespeed.com/doc/build_ngx_pagespeed_from_source

**Comment by sclevine** [comment]
This seems reasonable to me. Pagespeed is a popular NGINX module that is widely used, and including it as a dynamic module would have no runtime impact.

My only concern is the use case. How useful is pagespeed for serving static content?

**Comment by CAFxX** [comment]
@sclevine we often use staticfile as a reverse proxy

**Comment by sclevine** [comment]
I'm becoming more convinced that we should create a separate NGINX buildpack that isn't geared towards static content and provides multiple versions of NGINX. 

Most of the logic in this buildpack is about generating an nginx.conf file that serves static content. None of the directives in the Staticfile are respected if you replace nginx.conf. Staticfile.auth is even ignored if you replace it, which is pretty scary.

Furthermore, only a single version of NGINX is provided, which leaves you with no rollback strategy if you encounter a bug in a more complex NGINX feature after upgrading the buildpack.

@dgodd, any thoughts on this?

**Comment by dgodd** [comment]
@sclevine I definitely think we should create a reverse proxy buildpack. I wonder if it should use nginx or something else (eg haproxy, varnish). Using a specific reverse proxy might enable us to more easily add features of strong interest to reverse proxies (but not web servers).

**Comment by dgodd** [comment]
@CAFxX With respect to the above discussion of static buildpack vs. reverse proxy buildpack, could we ask what you are using a reverse proxy for? For instance does your app need to do both static files and reverse proxy? What sorts of things does the static buildpack reverse proxy solve for you that https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#routes don't?

We believe that many people are using the static buildpack as a reverse proxy, and would like to work out if we can serve them better either with static buildpack or an alternative.

**Comment by CAFxX** [comment]
@dgodd we run on prem and some of the applications that are behind the reverse proxy are not even running on CF, so routes are automatically out. In addition to that routes can't do most things that a reverse proxy (nginx) can do: transform requests/responses, caching, compression, complex routing (e.g. based on headers) or running ngx_pagespeed (to name just a few).

> We believe that many people are using the static buildpack as a reverse proxy, and would like to work out if we can serve them better either with static buildpack or an alternative.

Both are fine IMHO. To address @sclevine's concern that some staticfile buildpack features are silently disabled by a custom `nginx.conf`, I would like to propose a simple solution: if a custom `nginx.conf` is provided *and* any of the "signaling mechanisms" (e.g. `Staticfile`, `Staticfile.auth`, `FORCE_HTTPS` and so on) are used, staging should fail with a clear message that explains that custom a custom nginx.conf is not compatible with the other staticfile configuration options.

**Comment by sclevine** [comment]
Sorry for the long delay here. After extended discussion, we plan to introduce an nginx-buildpack that requires a user-supplied nginx.conf and provides multiple patch versions and version lines of NGINX. We plan to add a large assortment of dynamic NGINX modules (pagespeed, openresty, etc.) in the new buildpack. A formal proposal for this new buildpack will be sent to the cf-dev mailing list.

**Comment by bettyCornfeld** [comment]
When do you estimate the nginx-buildpack will be available?

**Comment by CAFxX** [comment]
@sclevine do you have any link to a story I can follow?

Also, if we're going to have a separate buildpack, https://github.com/cloudfoundry/staticfile-buildpack/issues/106 is going to apply also to the new buildpack.

**Comment by sclevine** [comment]
@bettyCornfeld @CAFxX follow #107 for updates.

#106 will definitely apply to the new buildpack 😄
