### ISSUE TITLE
Can't specify ipv6 address in ip filter

### ISSUE THREAD

**Issue by jtwaleson** [cloudfoundry/staticfile-buildpack#109]
I'm including custom config to block access to my app based on the `X-Real-IP` / `X-Forwarded-For` header. If I limit it to IPv4 addresses, it works fine, but when I include an IPv6 range, I see `[emerg] 226#0: invalid parameter "::/128"...`.

The result is that none of my IPv6 users can access the application.

```
    satisfy all;
    allow 1.2.3.4/32;
    allow 2001:0db8:85a3:0000:0000:8a2e:0370:7334/128;
    deny all;
````

I think this can be solved by including `--with-ipv6` [in the nginx build specification](https://github.com/cloudfoundry/binary-builder/blob/master/recipe/nginx.rb).

**Comment by sclevine** [comment]
Cloud Foundry currently only supports ipv6 [via an external load balancer](https://docs.cloudfoundry.org/adminguide/enabling_ipv6.html). This makes me hesitant to add ipv6 support to NGINX. Are you sure that ipv6 support is necessary and sufficient to filter those headers? Have you tried this?

**Comment by jtwaleson** [comment]
The external load balancer is the scenario indeed.

But: I am a noob. I tested this with an outdated version of the buildpack & nginx package (1.9.13). It already works with the latest version. Looking at the [nginx changelog](http://nginx.org/en/CHANGES) I suspect this fixed it:

```
...
Changes with nginx 1.11.5    11 Oct 2016
* Change: the --with-ipv6 configure option was removed, now IPv6 support is configured automatically.
....
```

Sorry for wasting your time.
