### ISSUE TITLE
Add AWS Auth module with NGINX

### ISSUE THREAD

**Issue by bettyCornfeld** [cloudfoundry/staticfile-buildpack#112]
Hello,

I use nginx proxy with S3 object store and  because the AWS auth module is missing I can't configure the nginx to work with S3 
What version of Cloud Foundry and CF CLI are you using? 
**cf version 6.26.0+9c9a261.2017-04-06**

What version of the buildpack you are using?
**Buildpack version 1.4.11**

If you were attempting to accomplish a task, what was it you were attempting to do?
**Use nginx server as reverse-proxy for S3 object store.
In nginx.conf file I defined a location directive containing proxy_pass, aws_access_key_id, aws_secret_access_key**

What was the actual behavior?
**I receive unknown directive "aws_access_key_id" error when pushing the app.**

Thanks,
Betty

**Comment by sclevine** [comment]
Hi @bettyCornfeld,

The Staticfile buildpack is intended to host static content, not reverse proxy other services. Because we regularly receive requests for a buildpack that provides NGINX, we have plans to introduce an nginx-buildpack in the near future. See #107.
