### ISSUE TITLE
Nginx.conf is copied and not moved leaving it accessible publicly

### ISSUE THREAD

**Issue by ballwood** [cloudfoundry/staticfile-buildpack#113]
**What version of the buildpack you are using?**

v1.4+

**If you were attempting to accomplish a task, what was it you were attempting to do?**

Use a custom nginx.conf by placing it in the directory cf push is called in.

**What did you expect to happen?**

Custom nginx.conf gets moved from public to nginx/nginx.conf

**What was the actual behavior?**

nginx.conf is copied. leaving nginx.conf exposed in the public directory for anyone to download

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [X] I have included steps for reproduction

originally in <1.4 this was handled by doing a mv in boot.sh for any nginx.conf in the root, see [here](https://github.com/cloudfoundry/staticfile-buildpack/blob/206728f929a69ed12570ee755b72e4cd5457745d/bin/boot.sh#L24)

in 1.4+ it has been changed to a copy which leaves nginx.conf in the public directory, see [here](https://github.com/cloudfoundry/staticfile-buildpack/blob/c88520c67ec01659751c88acafeee50e059d7852/src/staticfile/finalize/finalize.go#L307)

**Comment by sclevine** [comment]
Hi @ballwood,

Thanks for the report! This is fixed in [v1.4.15](https://github.com/cloudfoundry/staticfile-buildpack/releases/tag/v1.4.15).
