### ISSUE TITLE
Replacing OOB NGINX with a custom build is not working

### ISSUE THREAD

**Issue by luckyabhishek** [cloudfoundry/staticfile-buildpack#115]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
API Version : 2.94
CLI Version : 6.28.0

What version of the buildpack you are using?
Latest 

If you were attempting to accomplish a task, what was it you were attempting to do?
I want a NGINX in CF with http substitution module. 

What did you expect to happen?
I tried to replace the OOB build in the manifest.yml with my own custom build of NGINX. Basically I edited the URI and MD5 hash of the nginx build. This new build had http module built into it and was compiled on ubuntu 16.04 docker container. 

What was the actual behavior?
The container never starts and I get the following errors in the log.

2017-09-15T14:10:56.53+0530 [APP/PROC/WEB/0] ERR + /home/vcap/app/start_logging.sh
   2017-09-15T14:10:56.53+0530 [APP/PROC/WEB/0] ERR + nginx -p /home/vcap/app/nginx -c /home/vcap/app/nginx/conf/nginx.conf
   2017-09-15T14:10:56.53+0530 [APP/PROC/WEB/0] ERR /home/vcap/app/boot.sh: 4: /home/vcap/app/boot.sh: nginx: not found

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Hi @luckyabhishek,

Have you compared the tgz archive of your custom build of NGINX to the official one in manifest.yml? If it looks similar, can you provide a link to your custom tgz archive?

**Comment by luckyabhishek** [comment]
Hi @sclevine  
Thanks for the response. You are right... my folder structure was different as it had one more sub level folder for nginx. 
I changed the structure and it rocked :)
Thanks againf or the quick help.
