### ISSUE TITLE
Add ability to declare a custom 404 page without having to provide a custom nginx.conf

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/staticfile-buildpack#116]
Hello Buildpacks team,

I was working on migrating an existing AWS S3-hosted static site over to using CF and for the most part everything went smoothly.  One thing that was a bit of a headache, though, was getting a custom 404 page set up.  

I expected to be able to configure something in the `Staticfile` to point to a specific 404 document (similar to how [S3 does it](http://docs.aws.amazon.com/AmazonS3/latest/dev/CustomErrorDocSupport.html)) or for there to have been a prescribed default path like `/404.html` (similar to how [Github Pages does it](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/)).

However, the only way I found to do it required supplying a custom `nginx.conf` file.  I ended up having to `cf ssh` on to the app and just copied the one that's generated by default then appended the necessary config.  This involved more nginx knowledge than I felt was necessary for this task and I worry that I'll miss out on future changes to the default nginx config.

I read through #77 and understand the rationale behind not implementing the ability to inject arbitrary config into the generated `nginx.conf`, but I think a more user-friendly way to include a custom 404 page would be valuable.

Thanks!

**Comment by sclevine** [comment]
You should be able to accomplish this with the `location_include` Staticfile directive, without replacing nginx.conf. That said, this seems like a reasonable feature for hosting static content, so we will consider adding a Staticfile directive just for custom status pages.

**Comment by tcdowney** [comment]
Ah, I wasn't aware of that directive. That helps a lot in the meantime, thanks!

**Comment by sclevine** [comment]
Custom status pages has been scheduled: https://www.pivotaltracker.com/story/show/151158550

**Comment by tcdowney** [comment]
Thanks @sclevine and everyone who worked on it, works great! 🎉
