### ISSUE TITLE
Running integration/unit test fails on Mac OS 

### ISSUE THREAD

**Issue by rakrup** [cloudfoundry/staticfile-buildpack#118]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

What version of the buildpack you are using?
master

If you were attempting to accomplish a task, what was it you were attempting to do?
trying to run the integration test and unit test on a Mac OS

What did you expect to happen?
Tests to execute without erring out

What was the actual behavior?
Tests can't be executed as readlink -f fails on Mac . The correct command would be stat -f on a Mac.

**Comment by rakrup** [comment]
Propsed a change from my end. Please review and merge if it seems legit.

**Comment by sclevine** [comment]
Closing this in favor of #118.
