### ISSUE TITLE
open() on /dev/stdout fails

### ISSUE THREAD

**Issue by bensteinert** [cloudfoundry/staticfile-buildpack#122]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
"api_version": "2.65.0",
cf version 6.29.0+ff886fa93.2017-07-24

What version of the buildpack you are using?
1.4.17

If you were attempting to accomplish a task, what was it you were attempting to do?
cf push of an arbitrary (even empty staticfile app)

What did you expect to happen?
Correct start of the nginx process

What was the actual behavior?
process terminated with log output:
2017-10-17T16:24:15.54+0200 [APP/PROC/WEB/0] ERR + exec nginx -p /home/vcap/app/nginx -c /home/vcap/app/nginx/conf/nginx.conf
   2017-10-17T16:24:15.55+0200 [APP/PROC/WEB/0] ERR 2017/10/17 14:24:15 [emerg] 13#0: open() "/dev/stdout" failed (13: Permission denied)

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sclevine** [comment]
Hi @bensteinert,

We've received a few reports about `/dev/stdout` not being openable after this release. Can you provide more details about your CF installation? Do you know what cf-release version you are pushing to?

**Comment by bensteinert** [comment]
Hi @sclevine,
sorry, can't give exact numbers, because the instance is hosted by a customer I work for. But as far as I know, it is a release from end of 2016. I try to gather more details, if no one else can help out quicker, with more detailed issue reports.

**Comment by sclevine** [comment]
We reverted the breaking change on master. The release that included it was never packaged, just merged to master, so this only broke users who were running old foundations and had the buildpack github repo URL specified.
