### ISSUE TITLE
proxy_pass directive in location block not working

### ISSUE THREAD

**Issue by rbedemann** [cloudfoundry/staticfile-buildpack#125]
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**
2.98.0

**What version of the buildpack you are using?**
-----> Staticfile Buildpack version 1.4.16

**If you were attempting to accomplish a task, what was it you were attempting to do?**
We are trying to add a proxy_pass directive to our nginx configuration to proxy all http requests on /api to our backend which has another domain.

**What did you expect to happen?**
We expected all requests on /api to get proxied to our backend.

**What was the actual behavior?**
The requests ended up on our staticfile container. This worked with version 1.4.15. We expect that this is related to https://www.pivotaltracker.com/story/show/148630045

**Please confirm where necessary:**
* [ ] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

**Steps for reproduction:**

1. Create a config file in `nginx/conf/includes/proxy.conf`:
`location /api {
    proxy_pass https://domain-of-backend.com/;
}`
2. Enable pushstate on nginx via `pushstate: enabled` in Staticfile
3. Add location include via `location_include: includes/*.conf` in Staticfile

**Important:** As mentioned before, this worked with version 1.4.15 where all nginx config directives have been in the location block and not in the server block

**Comment by sclevine** [comment]
Thanks for the report @rbedemann, we'll take a look.

**Comment by dgodd** [comment]
@rbedemann This is an interaction specifically beween `location / proxy_pass` and `pushstate: enabled`. As a short term fix, you can disable `pushstate: enabled` and add a new file `nginx/conf/includes/pushstate.conf` with contents 
```
if (!-e $request_filename) {
  rewrite ^(.*)$ / break;
}
```

We are currently working on a longer term answer

**Comment by sclevine** [comment]
Fixed on `develop`: bea124ec65ba85af5c55fe49ba85f325beffd39e

A more complete plan to address issues like this is mentioned here: https://github.com/cloudfoundry/staticfile-buildpack/issues/103#issuecomment-337036547
