### ISSUE TITLE
Add ability to use environmental variables inside location includes.

### ISSUE THREAD

**Issue by nathanmarks** [cloudfoundry/staticfile-buildpack#126]
When you override the entire nginx.conf, you can use environmental variables in your config. 

When using the location includes feature, the variable substitution possible in the main template does not work.

Would it be possible to add this feature?

**Comment by sclevine** [comment]
Hi @nathanmarks,

This is already prioritized here: https://www.pivotaltracker.com/story/show/149857432

And also discussed here: https://github.com/cloudfoundry/staticfile-buildpack/issues/103
