### ISSUE TITLE
Errors while attempting to deploy simple html code

### ISSUE THREAD

**Issue by Franjey** [cloudfoundry/staticfile-buildpack#132]
Hi everyone, I am getting an error when deploying the application. What I am trying to do is deploy a simple "Hello world" html page.:

This is my setup:
![image](https://user-images.githubusercontent.com/11093607/34833620-a1b30556-f6ce-11e7-95f1-048318279264.png)

![image](https://user-images.githubusercontent.com/11093607/34833639-afe0198e-f6ce-11e7-8664-af9d946b8275.png)

![image](https://user-images.githubusercontent.com/11093607/34833692-d1f1a6aa-f6ce-11e7-859c-6977cbc75016.png)

These are the errors I get when I try to deploy: Application startup process timeout

When I check the console:
![image](https://user-images.githubusercontent.com/11093607/34833757-ef78af98-f6ce-11e7-9a84-7117ef88627a.png)

Does someone knows how to fix this? 

Thanks!

**Comment by dgodd** [comment]
@Franjey To use the staticfile buildpack you will need to create a file `Staticfile` (you do not need to put anything in it, although you can).

See: https://docs.cloudfoundry.org/buildpacks/staticfile/index.html#staticfile and https://docs.cloudfoundry.org/buildpacks/staticfile/index.html#config-process

**Comment by Franjey** [comment]
Hi @dgodd thanks for the above. Phew.. was a simple solution.

Got one more question: I noticed staticfile-buildpack does not include php. Would it be possible to use multiple buildpacks in my manifest.yml file? If so, how would that work?

I got the following php buildpack: https://github.com/cloudfoundry/php-buildpack

Thank you and have a nice day.

**Comment by dgodd** [comment]
@Franjey PHP buildpack uses either nginx or apache httpd to as a webserver. You can use that to serve your static files. Does that solve the problem? If so then you won't need both

**Comment by Franjey** [comment]
@dgodd  You mean I could just insert the PHP code into the index.html file and use as is? Leaving the Staticfile without any content

**Comment by sclevine** [comment]
Closing as resolved.

@Franjey this buildpack is for apps that just serve static content. You can't use this buildpack for apps that require PHP. To use PHP, your app must be configured to work with the PHP buildpack. [See here](http://docs.cloudfoundry.org/buildpacks/php/index.html).
