### ISSUE TITLE
Nested Custom location directives are overridden by push_state

### ISSUE THREAD

**Issue by prettyClouds** [cloudfoundry/staticfile-buildpack#133]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
   "min_cli_version": "6.7.0",
   "min_recommended_cli_version": "6.11.2",
   "api_version": "2.75.0",
```
`cf version 6.23.0+c7866be18-2016-12-22`

What version of the buildpack you are using?
`v1.4.16`

If you were attempting to accomplish a task, what was it you were attempting to do?
we were attempting to return a 500 when hitting a specific route.

What did you expect to happen?
for the route to return a 500

What was the actual behavior?
the route returned a 200 and ignored our nginx directive

We talked with @dgodd about this issue.  It looks like the nested location directives do not work when push_state is enabled, because in the template the push_state directives come before the custom location directives.  https://github.com/cloudfoundry/staticfile-buildpack/blob/master/src/staticfile/finalize/data.go#L96-L99

**Comment by sclevine** [comment]
@dgodd I don't think we can fix this without radically changing the behavior of existing apps.

Requests like this will be addressed by the nginx-buildpack.
