### ISSUE TITLE
CF Push doesn't find the Staticfile

### ISSUE THREAD

**Issue by bigorangemachine** [cloudfoundry/staticfile-buildpack#134]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.101.0",
}
```

What version of the buildpack you are using?
`1.4.20`

If you were attempting to accomplish a task, what was it you were attempting to do?
Push Staticfile

What did you expect to happen?
Staticfile to be applied at buildtime

What was the actual behavior?
Staticfile does not configure nginx

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

Log output not needed as there is no error.  However when you follow the steps to reproduce the `-----> Enabling pushstate` does not appear

## How to reproduce:

Setup a frontend project like `create-react-app` (react-scripts) project; but anything that replicates `project/build/` setup.

Run the build script to create a `build/` directory; or just place some assets in a `build/` directory (`project/build/`).

Create a `manifest.yml` with your required settings in the project root (`project/manifest.yml`)

Create a `Staticfile` with `pushstate: enabled` and place it in the `build/` directory (`project/build/Staticfile`)

Run `cf push -p build/` with a CWD of `project/` (from the project root not the build folder)

Note the `-----> Enabling pushstate` does not appear`

Note the server doesn't act like the push state is enabled.

## The Issue

`Staticfile` is only found via CWD.

### Why its an issue

When using a tool like concourse CI it doesn't find the Staticfile and the documentation isn't clear that this is the issue.

### Recommendation 

Allow an argument to specify a path to the `Staticfile` or look for `Staticfile` configs inside the directory that is being pushed.

**Comment by sclevine** [comment]
Hi @bigorangemachine,

The `Staticfile` is parsed by the buildpack during staging. The cf CLI has no knowledge of it. If the `Staticfile` is available at the app root, and you push the app with the staticfile buildpack, the `Staticfile` should be respected.

Can you push a sample app to Github that you believe demonstrates incorrect behavior?

**Comment by bigorangemachine** [comment]
Sorry this was a months old bug I am late in filing.

It looks like the bug got fixed.  I have tried replicating the issue as I outlined before (I have the code in a private repo) but I can't replicate even though I am following the steps I've used before.

Thanks for your quick reply!
