### ISSUE TITLE
staticfile_buildpack compile nginx with additional modules

### ISSUE THREAD

**Issue by dorlandode** [cloudfoundry/staticfile-buildpack#135]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
6.29.0+ff886fa.2017-07-24
"api_version": "2.98.0"

What version of the buildpack you are using?
staticfile_buildpack

If you were attempting to accomplish a task, what was it you were attempting to do?
I need to know if there is a way to compile nginx with additional modules.  I want to use http_sub_module, but the nginx binary in the deployed app wasn't compile with that option.

What did you expect to happen?
Hoping I can configure the app to use additional nginx modules.

What was the actual behavior?
I can't find a way to do this currently.

**Comment by sclevine** [comment]
Can you describe your use case? Do you need this module to serve static content?

If not, we would definitely consider compiling NGINX to support this module in the nginx-buildpack. It isn't publicly available yet, but it will be [here](https://github.com/cloudfoundry/nginx-buildpack) very soon.

**Comment by dorlandode** [comment]
Specifically I am wanting to use a reverse proxy. When the content comes back I would like to rewrite It, for example, I may want to modify urls in hyper links, etc..  http_sub_module has worked for me in the past.

**Comment by sclevine** [comment]
The experimental NGINX buildpack is available here: https://github.com/cloudfoundry/nginx-buildpack
(See the `develop` branch for better usage docs.)
