### ISSUE TITLE
ERR when deploying a simple static file application.

### ISSUE THREAD

**Issue by ArunSridharanDevOps** [cloudfoundry/staticfile-buildpack#136]
Deploying a simple html file results in the following error in logs. Although the cf push is sucessfull and app is accessible we are wondering why this error appears in the syslog.

2018-01-22T10:56:22.90-0500 [APP/0] ERR + /home/vcap/app/start_logging.sh
2018-01-22T10:56:22.90-0500 [APP/0] ERR + nginx -p /home/vcap/app/nginx -c 

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
bash-4.1$ cf curl /v2/info
{
   "name": "",
   "build": "",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.cfsys-gcg-cert-mwdc.nam.nsroot.net",
   "token_endpoint": "https://uaa.cfsys-gcg-cert-mwdc.nam.nsroot.net",
   "min_cli_version": "6.7.0",
   "min_recommended_cli_version": "6.11.2",
   "api_version": "2.58.0",
   "app_ssh_endpoint": "ssh.cfsys-gcg-cert-mwdc.nam.nsroot.net:2222",
   "app_ssh_host_key_fingerprint": "5f:92:41:4c:d7:f2:94:c8:a7:f3:94:29:94:2c:b3:d6",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.cfsys-gcg-cert-mwdc.nam.nsroot.net/routing",
   "logging_endpoint": "wss://loggregator.cfsys-gcg-cert-mwdc.nam.nsroot.net:443",
   "doppler_logging_endpoint": "wss://doppler.cfsys-gcg-cert-mwdc.nam.nsroot.net:443",
   "user": "a4e91d29-eb27-4b08-92bc-358fe38bb0aa"
}

bash-4.1$ cf version
cf version 6.34.1+bbdf81482.2018-01-17

What version of the buildpack you are using?
V 1.4.21
V 1.4.14

Same error occurs in both the versions.

If you were attempting to accomplish a task, what was it you were attempting to do?
Pushing a simple staticfile application results in an error in the logs.
Although the application deployment is successful there appears to an error in the logs.

   2018-01-22T10:56:22.53-0500 [CELL/0] OUT Successfully created container
   2018-01-22T10:56:22.75-0500 [CELL/0] OUT Starting health monitoring of container
   2018-01-22T10:56:22.90-0500 [APP/0] **ERR** + /home/vcap/app/start_logging.sh
   2018-01-22T10:56:22.90-0500 [APP/0] **ERR** + nginx -p /home/vcap/app/nginx -c /home/vcap/app/nginx/conf/nginx.conf
   2018-01-22T10:56:24.81-0500 [CELL/0] OUT Container became healthy
   2018-01-22T10:56:26.80-0500 [CELL/0] OUT Destroying container
   2018-01-22T10:56:27.02-0500 [CELL/0] OUT Successfully destroyed container
 

What did you expect to happen?
Expected application to deployed without any Error.

What was the actual behavior?
Pushing a simple staticfile application results in an error in the logs.
Although the application deployment is successful there appears to an error in the logs.
The sample app doesn't have any custom ngnix config. It just has an html file.

Please confirm where necessary:
* [* ] I have included a log output
* [*] My log includes an error message
* [*] I have included steps for reproduction
[staticfile.log](https://github.com/cloudfoundry/staticfile-buildpack/files/1652612/staticfile.log)

**Comment by dgodd** [comment]
@ArunSridharanDevOps That is a simple informational output telling you what is running. Is your question why is it printed on STDERR rather than STDOUT? (I don't actually know, and will look)

**Comment by ArunSridharanDevOps** [comment]
Thanks for the response @dgodd . The concern was due to the fact that its getting printed as an ERR message. If this is an informational message it should be printed in STDOUT.

**Comment by dgodd** [comment]
@ArunSridharanDevOps for better or worse this is how bash works. We could convert it to STDOUT but that would have other effects

**Comment by ArunSridharanDevOps** [comment]
Thanks for the clarification.
