### ISSUE TITLE
Trailing slash redirect doesn't respect protocol

### ISSUE THREAD

**Issue by TuckerWhitehouse** [cloudfoundry/staticfile-buildpack#137]
*What version of the buildpack you are using?*
1.4.13

*What was it you were attempting to do?*
Navigate to a path like `https://example.com/something` which corresponds to a folder.

*What did you expect to happen?*
The browser would be redirected to `https://example.com/something/` (trailing slash)

*What was the actual behavior?*
The browser is redirected to `http://example.com/something/` (trailing slash, http)

SSL is terminated at the router, and the original protocol is sent along in the `X-Forwarded-Proto` header, but this does not seem to be respected by the nginx trailing slash redirect.

**Comment by sclevine** [comment]
Hi @TuckerWhitehouse,

Thanks for the report. We are already aware of this issue and are waiting for the routing team to tell us whether they are open to re-writing the `Location` header to correct the behavior. The `X-Forwarded-Proto` header is non-standard[1], and intentionally ignored by NGINX.

 @shalako were you able to determine whether similar routers or load balancers re-write `Location` headers?

[1] https://tools.ietf.org/html/rfc7239

**Comment by sclevine** [comment]
@shalako any updates here?

**Comment by shalako** [comment]
We have not made any effort on this issue, and are unlikely to given our focus on replacing Gorouter with Envoy.

**Comment by sclevine** [comment]
Thanks @shalako, we will consider re-writing `Location` headers in the Staticfile and PHP buildpacks.

Super excited to see Envoy in CF!

**Comment by sclevine** [comment]
Re-opening as other headers are not addressed yet.

**Comment by pimlottc-gov** [comment]
This is a major issue for us in our application, as port 80 is blocked for security reasons (government environment), so these redirects are broken.

**Comment by pimlottc-gov** [comment]
The workaround I've found is to set the `http_strict_transport_security` option in the [Staticfile file configuration](https://docs.cloudfoundry.org/buildpacks/staticfile/index.html#staticfile):

```
# Cloudfoundry sends redirects to http
# this property sets a header to force the browser to always use https instead
http_strict_transport_security: true 
```

**Comment by Zanadar** [comment]
@pimlottc-gov Thanks for the note. Closing this issue.

**Comment by pimlottc-gov** [comment]
@Zanadar A workaround is good to have, but the issue should really be fixed in the buildpack itself...

**Comment by Zanadar** [comment]
I agree. We’ll make an effort to fit this into our backlog.

**Comment by dfreilich** [comment]
@pimlottc-gov It looks like this was added in 9a415a9287fe2e31113d9283f4e5cfd503fbb2b7. Thanks for the push to add it in!

**Comment by vmpn** [comment]
FYI, this is still an issue for content that has index.html and does not want to enable directory listing as currently the only way to enable  "absolute_redirect off;" is via DirectoryIndex directive.  Would be great if ""absolute_redirect off;" could be enabled on its own

**Comment by dfreilich** [comment]
Hey @vmpn, I believe development for this has stopped, with the release of [paketo-buildpacks](https://www.cloudfoundry.org/blog/everything-you-need-to-know-about-paketo-buildpacks/). I would reach out to them on the [paketo slack](https://slack.paketo.io/) and see whether there is a new paketo staticfile buildpack.

**Comment by vmpn** [comment]
> Hey @vmpn, I believe development for this has stopped, with the release of [paketo-buildpacks](https://www.cloudfoundry.org/blog/everything-you-need-to-know-about-paketo-buildpacks/). I would reach out to them on the [paketo slack](https://slack.paketo.io/) and see whether there is a new paketo staticfile buildpack.

@dfreilich  Thank you for letting me know
