### ISSUE TITLE
[Question] How to enable underscores_in_headers?

### ISSUE THREAD

**Issue by fbiville** [cloudfoundry/staticfile-buildpack#140]
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**

```
➜  nginx-test cf curl /v2/info
{
 // truncated because of sensitive client information
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.94.0"
}
➜  nginx-test cf version
cf version 6.35.2+88a03e995.2018-03-15
```

**What version of the buildpack you are using?**
`Staticfile Buildpack version 1.4.21`

**If you were attempting to accomplish a task, what was it you were attempting to do?**
We're trying to make this Nginx configuration work (`includes/cookie.conf`):
```
set $segment default_value;
if ($http_custom_header ~* "some\.thing$") {
  set $segment custom_value;
}
add_header Set-Cookie "segment=$segment;Path=/;";
```
And our `Staticfile` contains:
```
location_include: includes/*.conf
```

**What did you expect to happen?**
We expected to see `custom_value` in the response `Set-Cookie` header when `CUSTOM_HEADER` header is set in the request.

**What was the actual behavior?**
This does not work because the header is `CUSTOM_HEADER` (underscore), not `CUSTOM-HEADER` (hyphen), we unfortunately have no control over it.

We would like to enable `underscores_in_headers`(http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers), but we are not sure how we are supposed to specify a custom `nginx.conf` (we could not find enough information in http://docs.cloudfoundry.org/buildpacks/staticfile/#custom_nginx_configuration).

Please confirm where necessary:
* [ ] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by ameyer-pivotal** [comment]
@fbiville With the staticfile buildpack, you should be able to provide a custom `nginx.conf` in your app root that will get picked up and applied when you `cf push`. For reference, take a look at the last row of the table in http://docs.cloudfoundry.org/buildpacks/staticfile/#config-process.

You could also look into the [nginx buildpack](https://github.com/cloudfoundry/nginx-buildpack). It's still "experimental", but is more aimed at custom nginx configuration than the staticfile buildpack.

We'll go ahead and close this, but if we missed something or you still can't get it to work, feel free to open with additional info.

**Comment by fbiville** [comment]
Then I have to replace the entire `nginx.conf` to be able to define the only setting I am actually interested in. Is that correct or am I missing something?

If so, I agree this issue is a not blocker because there is a solution today.
However, it seems to me that this approach is not super safe, as one has to replicate the implicit default Nginx configuration (which may change over time).
