### ISSUE TITLE
FORCE_HTTPS doesn't persist requested name. 

### ISSUE THREAD

**Issue by dmarmugi** [cloudfoundry/staticfile-buildpack#141]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "",
   "build": "",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.g4.app.cloud.comcast.net",
   "token_endpoint": "https://uaa.g4.app.cloud.comcast.net",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.94.0",
   "app_ssh_endpoint": "ssh.g4.app.cloud.comcast.net:2222",
   "app_ssh_host_key_fingerprint": "12:c6:ed:80:48:83:30:28:b5:f3:4a:c0:13:f5:c1:19",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.g4.app.cloud.comcast.net:443",
   "routing_endpoint": "https://api.g4.app.cloud.comcast.net/routing"
}
cf version 6.35.0+5c7de3e32.2018-03-08
```

What version of the buildpack you are using?
`staticfile_buildpack-cached-v1.4.21.zip`

If you were attempting to accomplish a task, what was it you were attempting to do?
Force HTTPS behind a CNAME/load balancer

What did you expect to happen?
The app should redirect to https on the requested name:
`http://cname.comcast.com --> 301 --> https://cname.comcast.com`

What was the actual behavior?
The app redirected to the local instance fqdn: 
`http://cname.comcast.com --> 301 --> https://myapp.g1.app.cloud.comcast.net`

Please confirm where necessary:
- [ ] I have included a log output
- [ ] My log includes an error message
- [x] I have included steps for reproduction

**Comment by sclevine** [comment]
Sorry for the delay. Closing this in favor of #142.
