### ISSUE TITLE
Staticfile buildpack license: MIT or Apache?

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/staticfile-buildpack#145]
Hi, I've seen that the Staticfile buildpack (in both - master and 1.4.24 level) specifies MIT in the License file and Apache V2 in the Notice file.

Could you please tell me what is the license of the Buildpack, MIT or Apache V2?

Thanks.

**Comment by sclevine** [comment]
I believe the current license is Apache v2, and it was originally MIT before being contributed to the CFF.

@christopherclark is this correct?

**Comment by luisapace** [comment]
Hi, do you have any news on this question? thanks for your collaboration.

**Comment by sclevine** [comment]
Updated to Apache 2.0 by Chris here: https://github.com/cloudfoundry/staticfile-buildpack/pull/147

**Comment by luisapace** [comment]
thanks!
