### ISSUE TITLE
Html 5 pushstate is not working

### ISSUE THREAD

**Issue by ittechsathish** [cloudfoundry/staticfile-buildpack#148]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "",
   "build": "",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.sys.cl-east-dev02.cf.ford.com",
   "token_endpoint": "https://uaa.sys.cl-east-dev02.cf.ford.com",
   "min_cli_version": "6.7.0",
   "min_recommended_cli_version": "6.11.2",
   "api_version": "2.75.0",
   "app_ssh_endpoint": "ssh.sys.cl-east-dev02.cf.ford.com:2222",
   "app_ssh_host_key_fingerprint": "24:17:cb:b3:fe:ee:d9:e5:12:24:96:ec:95:ea:cd:07",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.sys.cl-east-dev02.cf.ford.com/routing",
   "logging_endpoint": "wss://loggregator.sys.cl-east-dev02.cf.ford.com:443",
   "doppler_logging_endpoint": "wss://doppler.sys.cl-east-dev02.cf.ford.com:443",
   "user": "9eee6bdf-df83-4ea6-a293-494f8c4df72a"
}
cf version 6.37.0+a40009753.2018-05-25

What version of the buildpack you are using?

1.4.29

If you were attempting to accomplish a task, what was it you were attempting to do?

I am deploying react app which has html 5 push state enabled. After the deployment, the push state url is not working.

Requesting in browser - https://dev-app.something.clound.somexyz.com/login

What did you expect to happen?

It should show login page of web application.

What was the actual behavior?

response : 502 Bad Gateway: Registered endpoint failed to handle the request.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
You can enable push state with the `pushstate: enabled` directive in the Staticfile.

If that doesn't work, could you provide the output of a request made to the app with `curl -v`?

**Comment by ittechsathish** [comment]
How to make 
![image](https://user-images.githubusercontent.com/4141788/42824313-393bbe92-89fd-11e8-8987-c05caf982248.png)

**Comment by ittechsathish** [comment]
Issue fixed by adding `Staticfile` inside dist folder.

the above was not working when having manifest.yml like below.

buildpack: https://github.com/cloudfoundry/staticfile-buildpack
path: ./build
memory: 64M
env:
  FORCE_HTTPS: true
applications:
  - name: dev-dispatch-master-ford-ride

changed:

buildpack: staticfile_buildpack
path: ./build
memory: 64M
env:
  FORCE_HTTPS: true
applications:
  - name: dev-dispatch-master-ford-ride

**Comment by sclevine** [comment]
Glad you got it working! The Staticfile must be in the `build` directory specified by `path`, because that is the only directory pushed and provided to the buildpack.
