### ISSUE TITLE
Support for Environment Variables in Single-Page Webapp

### ISSUE THREAD

**Issue by fljmayer** [cloudfoundry/staticfile-buildpack#149]
A modern single-page webapp (e.g. with Angular) consists solely of static content (`index.html` and JavaScript files) that uses REST endpoints to retrieve all dynamic content. Such a single-page webapp may need some configuration to work in different environments. Using something like Node.js just for some configuration seems like overkill. 

Hence it would be nice if CloudFoundry environment variables could be made the available to the single-page webapp in the browser. I could imagine a static JSON file with placeholders for environment variables in strategic locations. When that file is served, the placeholders would be replaced with the actual values of the environment variables.

**Comment by SteveMartinAon** [comment]
We have a workaround for this issue writing the following python script in our .profile. 

`#!/bin/bash

function config {
python - <<END
import json, os;
vars = [key for key in os.environ.keys() if 'FRONTEND_CONFIG' in key]
filtered = { var: os.environ[var] for var in vars }
print(json.dumps(filtered))
END
}

OUTPUT=$(config)
CONFIG="function getFrontEndConfig() { return $OUTPUT; }"
echo $CONFIG > ./public/config.js
`

this file can then be loaded as a normal javascript file and assigned to a javacript variable.

One thing to be careful of is that not all variables should be send to the browser.

**Comment by miguellira** [comment]
According to this [2016 article](https://berndsgn.ch/posts/configure-front-end-apps-with-environment-variables-on-cloud-foundry/) at some point the buildpack was being parsed by Ruby and a custom nginx.conf could be provided that would be parse and generate the necessary config.

Looks like the buildpack is now written with Go, and providing a custom nginx.conf appears to no longer be recommended: https://github.com/cloudfoundry/staticfile-buildpack/blob/fa7ef2db27b6540fe42763f2a8d7fd212d219584/src/staticfile/finalize/finalize.go#L335

Would really like an official recommendation to this very common requirement. Thanks!

**Comment by SteveMartinAon** [comment]
Note that the example above does not require using a custom nginx.conf. It runs a command in the .profile to create a config.js file that can be downloaded containing the environment variables. 

This is obviously not an official recommendation, but has continued to work for us.

**Comment by miguellira** [comment]
@SteveMartinAon Thanks for following up and clarifying your solution. After re-reading your post and this [official doc](https://community.pivotal.io/s/article/How-to-Modify-the-Application-Container-Environment-prior-to-Application-Execution) it seems `.profile` would survive future revisions to the buildpack. :crossed_fingers:

**Comment by shanks3012** [comment]
We would suggest to use .profile in your app for environment variables as @SteveMartinAon suggested. Closing this out, feel free to reopen if you have further questions. Thanks.
