### ISSUE TITLE
IMPORTANT NOTICE: End of support for nginx versions 1.15.x after 2019-08-10

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/staticfile-buildpack#160]
The first release of the staticfile buildpack after August 10, 2019 will no longer include nginx versions 1.15.x. These nginx versions are no longer supported upstream. Please migrate your staticfile apps to supported versions of nginx before that time.

In addition, the default version of nginx will be bumped to 1.17.x at this time.

Note: Unless you are manually specifying a version of nginx for the buildpack to use, or you have customized your staticfile buildpack, no action is required.

**Comment by Kaatee** [comment]
Hi, do You know what is the end of support/EOL date for nginx 1.19.0?
