### ISSUE TITLE
Impossible de configure the large_client_header_buffers

### ISSUE THREAD

**Issue by xNok** [cloudfoundry/staticfile-buildpack#162]
What did you expect to happen?

In order to avoid returning 400 error, we need to define a bigger `large_client_header_buffers` , howerever properties in `server` context cannot be modified

What was the actual behavior?

Configuring in the staticfile the `large_client_header_buffers` property

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by dfreilich** [comment]
Hey @xNok , I see that this has been open for a bit. Is it still an ongoing issue? Can we get a sample app, to try and replicate the issue?

**Comment by mcunninghamirl** [comment]
Hey, I've encounter this exact issue today. The configuration I'm working with is an Microsoft Active Directory setup where a user is joined to many AD Groups, thus increasing the size of the JWT token provided.

Is there a solution when using Staticfile or should we just use Nginx buildpack instead?

**Comment by ryanmoran** [comment]
Fine-grained configuration of the `nginx.conf` is not something that is or will be supported in the Staticfile buildpack. We suggest that for that type of control you switch to using the NGINX buildpack and define your own `nginx.conf`. Thanks!
