### ISSUE TITLE
Defining Cache-Control header rules

### ISSUE THREAD

**Issue by vpicone** [cloudfoundry/staticfile-buildpack#164]
Hey! I'm trying to set Cache-Control headers for specific content in my static site. In the root of my project with the `Staticfile` I have `nginx/conf/includes/no-cache.conf`:

```
location ~* \.html$ {
    add_header Cache-Control "public, max-age=0, must-revalidate";
}

location /page-data {
    add_header Cache-Control "public, max-age=0, must-revalidate";
}

location = /sw.js {
    add_header Cache-Control "public, max-age=0, must-revalidate";
}
```

`Staticfile`:
```
root: public
location_include: includes/*.conf
force_https: true
```

Even though it the cf-cli reads `Enabling location include file includes/*.conf` when pushing, the rules aren't reflected in the app: https://cbn-test.mybluemix.net

In the of the fixtures/examples there's just a simple header that is applied to all requests. Is using location blocks like this supported?

Here's the source for my project:
https://github.com/vpicone/carbon-www/tree/add-cache-config

Thanks for your help!

**Comment by dfreilich** [comment]
Hey @vpicone , thanks for feedback! In general, when you are trying to set specific nginx rules, you should use the [nginx-buildpack](https://github.com/cloudfoundry/nginx-buildpack). I'll close this for now, but if it doesn't solve your issue, feel free to reopen the issue and continue the conversation!
