### ISSUE TITLE
HSTS header not included in Error responses

### ISSUE THREAD

**Issue by dmarmugi** [cloudfoundry/staticfile-buildpack#166]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

>    "api_version": "2.124.0",
> "osbapi_version": "2.14",
> cf version 6.46.1+4934877ec.2019-08-23

What version of the buildpack you are using?
v1.4.32, but I see the change I'm asking for isn't present in master

If you were attempting to accomplish a task, what was it you were attempting to do?
Set `Strict-Transport-Security` header

What did you expect to happen?
That it would be present on all responses. Per [this blog post](https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/), this is configurable: 
`add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;`
> The `always` parameter ensures that the header is set for all responses, including internally generated error responses. Older versions of NGINX (prior to version 1.7.5 or NGINX Plus R5) don’t support the `always` parameter and do not set the header on internally generated error responses.

What was the actual behavior?
nginx-generated error responses did not include the header

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by dmarmugi** [comment]
It was found in a pentest, excuse the ridiculous path :) 
```
$ curl -gi "https://<redacted>/a'a%5c'b%22c%3e%3f%3e%25%7d%7d%25%25%3ec%3c[[%3f$%7b%7b%25%7d%7dcake%5c/events"
HTTP/1.1 400 Bad Request
Content-Language: en
Content-Length: 800
Content-Type: text/html;charset=utf-8
Date: Wed, 06 Nov 2019 19:03:47 GMT
X-Vcap-Request-Id: ead0508e-bdce-4978-69de-0eb4431ca6ec
```

but against the root path:
```
$ curl -gi "https://<redacted>/"
HTTP/1.1 404 Not Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json;charset=UTF-8
Date: Wed, 06 Nov 2019 19:04:36 GMT
Expires: 0
Pragma: no-cache
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: 4f2940ab-1340-4117-4563-ef1929d10c31
X-Xss-Protection: 1; mode=block
Content-Length: 121
```

**Comment by dfreilich** [comment]
Thank you for commenting! Have you tried with the [nginx-buildpack](https://github.com/cloudfoundry/nginx-buildpack)? That allows a lot more configurability, and should allow for setting the HSTS policy.

**Comment by dmarmugi** [comment]
Ah, I see the `experimental` descriptor came off the nginx buildpack, nice. Nevertheless, supporting the `always` directive seems like it lines up with the documentation of the existing toggles, which say `...Causes NGINX to respond to all requests with the following header: ...`

Absent the `always` directive, per the NGINX docs it in fact only adds the response for response codes
> 200, 201 (1.3.10), 204, 206, 301, 302, 303, 304, 307 (1.1.16, 1.0.13), or 308 (1.13.0)

If it's `won't-fix` that's fine, I get that it's a bit of a corner case and maybe not worth a new feature-flag/behavior change, I think I'd maybe just expect an update to the docs in that case. Here's a repro against v1.5.1: 
```
$ curl -I 'https://response-test.g4.app.cloud.comcast.net/this-doesnt-exist'
HTTP/1.1 404 Not Found
Content-Length: 146
Content-Type: text/html; charset=utf-8
Date: Mon, 11 Nov 2019 20:58:03 GMT
Server: nginx
X-Vcap-Request-Id: fd8e2755-16b8-42ca-74ed-71430e1ca665


$ curl -I 'https://response-test.g4.app.cloud.comcast.net'
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 85
Content-Type: text/html; charset=utf-8
Date: Mon, 11 Nov 2019 20:58:08 GMT
Etag: "59dfbcbe-55"
Last-Modified: Thu, 12 Oct 2017 19:04:30 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Vcap-Request-Id: 7d86c3dd-ec6c-4533-4e8a-227dca604fe9


$ cat Staticfile
http_strict_transport_security_preload: true
http_strict_transport_security: true
http_strict_transport_security_include_subdomains: true
$
```

**Comment by robdimsdale** [comment]
Hi @dmarmugi,

Sorry for the delay. The [docs](https://docs.cloudfoundry.org/buildpacks/staticfile/index.html) have been updated to clarify which options the staticfile buildpack will pass to NGINX, and to use the [NGINX buildpack](https://docs.cloudfoundry.org/buildpacks/nginx/) if you need an option that isn't listed.

Given that, I'm going to close this issue.
