### ISSUE TITLE
Unable to switch between Nginx versions as implied in release notes

### ISSUE THREAD

**Issue by hodnett** [cloudfoundry/staticfile-buildpack#179]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf version 6.51.0+2acd15650.2020-04-07

What version of the buildpack you are using?

v1.5.9

If you were attempting to accomplish a task, what was it you were attempting to do?

I was hoping to switch to the bundled Nginx version 1.19.1 as described in the v1.5.9 release notes.

What did you expect to happen?

That CF would detect an existing buildpack.yml file that specifies which Nginx version to use. 

What was the actual behavior?

CF deploys the default 1.17.x regardless of inputs. 

However, it was suggested within the Slack channel that Staticfile buildpacks were never intended to have more than one Nginx binary, and that the _real_ issue is that the new Paketo pipeline is generating incorrect release notes. The Staticfile pipeline itself may have been incorrectly hooked up to the Nginx buildpack pipeline.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by floragj** [comment]
This issue has been resolved as of the [v1.5.10 release](https://github.com/cloudfoundry/staticfile-buildpack/releases/tag/v1.5.10). Going forward, only one version NGINX will be included in the buildpack's dependencies.
