### ISSUE TITLE
Error while updating to staticfile_buildpakc_1_5_5

### ISSUE THREAD

**Issue by ivanmarkov13** [cloudfoundry/staticfile-buildpack#181]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf curl /v2/info: "build": "2.4.15-build.3"
cf version: "cf version 6.42.0+0cba12168.2019-01-10"

What version of the buildpack you are using?
staticfile_buildpakc_1_5_5

If you were attempting to accomplish a task, what was it you were attempting to do?
I attempted to update the application to use the staticfile_buildpakc_1_5_5.

What did you expect to happen?
The application to start.

What was the actual behavior?
The following error occurred in PCF: 

[OUT] [31;1m**ERROR**[0m Invalid root directory: the application Staticfile specifies a root directory build that does not exist
[ERR] Failed to compile droplet: Failed to run finalize script: exit status 12

Please confirm where necessary:
* [V] I have included a log output
* [V] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by ForestEckhardt** [comment]
@ivanmarkov13 Are there any steps that you could give us to reproduce this problem? The error you have given us would indicate to me that the directory you are setting as your root directory does not exist or cannot be found inside the droplet with the given path. You may want to verify your root directory configuration.

**Comment by ivanmarkov13** [comment]
@ForestEckhardt I managed to resolve the issue by removing the root directory property from the Staticfile. I guess this way the buildpack is using some default root directory.

**Comment by ForestEckhardt** [comment]
Yep. The buildpack does set the root directory for you. Sounds like you have everything resolved so I am going to close this issue out. If you have any other issues relating to this feel free to reopen this issue!

**Comment by ivanmarkov13** [comment]
Thank you for the help!
