### ISSUE TITLE
Job (f0623c49-89d0-49d1-9161-a5dba084c1a1) failed: An unknown error occurred.

### ISSUE THREAD

**Issue by praful-dhabekar** [cloudfoundry/staticfile-buildpack#183]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "api_version": "2.151.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.run.pivotal.io/routing",
   "user": "0fa1ad78-2062-4d6c-b015-7818694a7154"
}
cf version 6.48.0+ca3deaa94.2019-12-04
```

What version of the buildpack you are using?
85714b6b-2bc9-4ae4-a05b-c8bb384d7b9f

If you were attempting to accomplish a task, what was it you were attempting to do?
I was just trying to push my angular app.

What did you expect to happen?
I expect it to deploy the app.

What was the actual behavior?
I am getting following error when I do `cf push`

![image](https://user-images.githubusercontent.com/23056780/90377718-0150a500-e096-11ea-9494-602c5e4bc0ac.png)

**_Steps for reproduction:_**
**manifest.yml**
```
---
applications:
- name: my-dashboard
  instances: 1
  buildpacks:
    - staticfile_buildpack
  memory: 128MB
```
**File structure: (Staticfile is empty)**

![image](https://user-images.githubusercontent.com/23056780/90378174-a4092380-e096-11ea-9b5e-4fac06aeeee2.png)

Run command `cf push`

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by sophiewigmore** [comment]
Hi @praful-dhabekar,
In order to trouble shoot this error, could you please provide more information about the nature of your app? The content of the `manifest.yml` you provided looks fine.
Additionally, could you please provide the output of `cf logs my-dashboard --recent`?

Has your app been pushed successfully before? If so, what's changed?

**Comment by robdimsdale** [comment]
Hi @praful-dhabekar, we're closing this issue now due to inactivity. If you encounter this problem again please feel free to re-open.
