### ISSUE TITLE
Need the latest fix of libbuildpack-dynatrace module in the staticfile buildpack

### ISSUE THREAD

**Issue by manitheja1** [cloudfoundry/staticfile-buildpack#184]
Hi Team,
I could see the libbuildpack dynatrace module in the staticfile buildpack is using 1.2.2 version. There has been a latest release(1.3.0) for the module which has a fix to customize oneagenturl(https://github.com/Dynatrace/libbuildpack-dynatrace/releases ).

We need that fix in the staticfile buildpack. I know. could you please help us in getting the new release which will have the latest release of libbuildpack-dynatrace?

Thanks,
Manitheja

**Comment by kvedurmu** [comment]
This has been bumped and released in https://github.com/cloudfoundry/staticfile-buildpack/releases/tag/v1.5.11
