### ISSUE TITLE
Unable to start app with staticfile_buildpack v1.5.12

### ISSUE THREAD

**Issue by raziuddincse** [cloudfoundry/staticfile-buildpack#186]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "IBM Cloud",
   "build": "v13.19.0",
   "support": "http://ibm.biz/bluemix-supportinfo",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://iam.cloud.ibm.com/cloudfoundry/login/uk-south",
   "token_endpoint": "https://uaa.eu-gb.cf.cloud.ibm.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "ssh.eu-gb.cf.cloud.ibm.com:2222",
   "app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.eu-gb.cf.cloud.ibm.com:443",
   "api_version": "2.153.0",
   "osbapi_version": "2.15",
   "user": "e05ed50b-d330-43dc-947a-3061843c2e04"
}
cf version 6.46.1+4934877ec.2019-08-23

What version of the buildpack you are using?
v1.5.12

If you were attempting to accomplish a task, what was it you were attempting to do?
Publishing Angular App using IBM Cloud Delivery Pipeline integrated with the GitHub Repository to Cloud Foundry Application instance

What did you expect to happen?
Application need to render properly when visiting the app url - https://my-display-app.eu-gb.mybluemix.net/

What was the actual behavior?
403 Forbidden
nginx
my-display-app.eu-gb.mybluemix.net/:1 GET https://my-display-app.eu-gb.mybluemix.net/ 403 (Forbidden)

Please confirm where necessary:
* [YES ] I have included a log output
* [YES ] My log includes an error message
* [ YES] I have included steps for reproduction
![error](https://user-images.githubusercontent.com/35959854/95793553-7988bf00-0d03-11eb-83b1-9333420dd35e.JPG)

**Comment by robdimsdale** [comment]
Hi @raziuddincse 

Sorry for the delay. Did you end up resolving this issue? I get a `404` when trying to access the link to the app above.

**Comment by robdimsdale** [comment]
I'll close this issue now; please feel free to re-open if you continue to encounter the original error.
