### ISSUE TITLE
Dependency Deprecation: nginx 1.19.x

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/staticfile-buildpack#207]
Deprecation date: 2021-05-01
Link: https://nginx.org/

**Comment by TisVictress** [comment]
The change to remove the deprecated nginx version also removes `dependency_deprecation_dates` from the manifest: https://github.com/cloudfoundry/staticfile-buildpack/commit/f3124b8a9bb9c32aa4bfcc2960a45a4af1ad11f8

**Comment by TisVictress** [comment]
Reverted [this change](https://github.com/cloudfoundry/staticfile-buildpack/commit/f3124b8a9bb9c32aa4bfcc2960a45a4af1ad11f8) since we should not remove dependencies until an engineering manager issues a 30-day notice.
We should create a new card to issue a 30-day notice.
