### ISSUE TITLE
IMPORTANT NOTICE: [staticfile-buildpack] Change of default nginx version after 2021-07-09

### ISSUE THREAD

**Issue by arjun024** [cloudfoundry/staticfile-buildpack#212]
The default version for NGINX will be updated to 1.21.x in the first release of the Staticfile buildpack after 2021-07-09.

We are giving a 30 day notice to inform users that the default version of NGINX in the Staticfile buildpack will be updated to the latest 1.21.x version in the first release of the Staticfile buildpack after 2021-07-09.

As always, the buildpacks team is happy to answer questions you may have about this deprecation in the #buildpacks Slack channel[1].

[1] - https://cloudfoundry.slack.com/archives/C02HWMDUQ

Thanks,
The Buildpacks Team

**Comment by shanks3012** [comment]
We have updated the default version line to 1.21.x earlier than the specified date in order to remove nginx versions < 1.20.x which included a critical CVE
