### ISSUE TITLE
IMPORTANT NOTICE: nginx versions 1.19.x, 1.20.x will be removed effective immediately

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/staticfile-buildpack#220]
Previously, a 30 day notice was sent alerting users of the staticfile buildpack that nginx version 1.19.x would be removed in July, 2021. It has been recognized that version lines older than 1.20.x of nginx contain a critical CVE and thus, the affected version lines will be removed in the next release of the nginx buildpack; earlier than previously stated.

Additionally, the default version of nginx will become 1.21.x in the next release. We do not anticipate your application to incur breaking changes, but please be ready to ensure your staticfile applications are configured to run with nginx 1.21.x.

Thanks,
Buildpacks Team

**Comment by robdimsdale** [comment]
No further action or notification needed; closing.
