### ISSUE TITLE
How to provide application context path while deploying through staticfile build pack

### ISSUE THREAD

**Issue by mdfirozansari** [cloudfoundry/staticfile-buildpack#283]
I am using the following version of cloud foundary 
{
   "name": "VMware Tanzu Application Service",
   "build": "2.11.10-build.1",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-11/pcf-release-notes/runtime-rn.html",
   "authorization_endpoint": "https://login.sys.dev.paas.bank.sbi",
   "token_endpoint": "https://uaa.sys.dev.paas.bank.sbi",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "app_ssh_endpoint": "ssh.sys.dev.paas.bank.sbi:2222",
   "app_ssh_host_key_fingerprint": "2b:aa:24:ad:92:5d:44:4f:7b:45:2a:6b:fc:3a:3e:78",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.sys.dev.paas.bank.sbi:443",
   "api_version": "2.164.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.sys.dev.paas.bank.sbi/routing",
   "user": "04e96b0e-654a-47d6-9ce6-4ba2b5498831"
}
cf version 6.51.0+2acd15650.2020-04-07

What version of the buildpack you are using? - v1.5.26

If you were attempting to accomplish a task, what was it you were attempting to do?

By default Staticfile build back deploy a application on '/' context path.  I want know how to deploy application on a given context path. 

What did you expect to happen?
index.html file should be serve when some try to hit the url like :  https://<hostname>/<context-path>/

**Comment by mdfirozansari** [comment]
support application context path is "abc" and hostname is "xyz", then index.html file should be serve through https://xyz/abc/

**Comment by arjun024** [comment]
You can use the `location_include` configuration in the Staticfile to add custom routes by providing NGINX configuration. See https://docs.cloudfoundry.org/buildpacks/staticfile/
E.g. of using this configuration: https://github.com/cloudfoundry/staticfile-buildpack/blob/v1.5.29/fixtures/pushstate_and_proxy_pass/nginx/conf/includes/proxy.conf

For more complex use cases, you should use https://github.com/cloudfoundry/nginx-buildpack
