### ISSUE TITLE
[QUESTION] When will staticfile-buildpack be available on cflinuxs4 stack?

### ISSUE THREAD

**Issue by DanieleStrafile** [cloudfoundry/staticfile-buildpack#351]
Hello everyone,

any updates on when the staticfile-buildpack be available on cflinuxs4 stack? 
In April 2023 cflinuxs3 stack will be removed from cloud foundry and the staticfile-buildpack has not yet been released on its successor stack, cflinuxs4. Are there plans to release it before April 2023? 
Thank you for your answers, I am sure there are many other teams pondering the same question :)

Regards,
Daniele

**Comment by DanieleStrafile** [comment]
Closing because I found out that work is in progress in that direction and can be tracked here:
https://github.com/cloudfoundry/staticfile-buildpack-release/issues/1

**Comment by arjun024** [comment]
https://github.com/cloudfoundry/staticfile-buildpack/releases/tag/v1.6.0
