### ISSUE TITLE
Release: staticfile-buildpack (Mar)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/staticfile-buildpack#354]
Release reminder for staticfile-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/staticfile-buildpack/compare/v1.6.0..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/staticfile-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by arjun024** [comment]
This was just released (https://github.com/cloudfoundry/staticfile-buildpack/releases/tag/v1.6.0) towards https://github.com/cloudfoundry/staticfile-buildpack-release/issues/1. No need of a new released
