### ISSUE TITLE
Ruby is not available in cflinuxfs4

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/staticfile-buildpack#359]
The buildpack writes a templated `nginx.conf` file to disk during the build phase. [This template](https://github.com/cloudfoundry/staticfile-buildpack/blob/610e933162c9d9154ab2b9f07472dbf116afe035/src/staticfile/finalize/data.go#L45-L163) contains ERB statements to read in environment variables. The buildpack also includes a [start script](https://github.com/cloudfoundry/staticfile-buildpack/blob/610e933162c9d9154ab2b9f07472dbf116afe035/src/staticfile/finalize/data.go#L23) that invokes `erb` to write out the results of the template before the application is started. With Ruby being removed from the `cflinuxfs4` stack, the buildpack can no longer perform the templating operation and results in built applications that will not run.

The buildpack will need to either bring along its own Ruby or be rewritten to not rely upon an installed Ruby for these operations.

**Comment by sophiewigmore** [comment]
Resolved by PR linked above, and released in v1.6.1 of the buildpack.
