### ISSUE TITLE
Be more specific about gzip

### ISSUE THREAD

**Issue by stubbornella** [cloudfoundry/staticfile-buildpack#43]
Your default config file turns gzip on:

https://github.com/cloudfoundry/staticfile-buildpack/blob/f3586855c97fafd875bc102ee81d8b7ba946eb29/conf/nginx.conf#L13

But, by default, this only turns on gzip for the `text/html` mime type. 

Would you be open to a PR to have a more complete gzip setup that covers common static assets like css, js, json, and xml? Something like this is working for us:

https://github.com/pivotal-cf/pivotal-ui/commit/99114e9bb719a8191b7626e4587e64f6ec14344f

**Comment by jtarchie** [comment]
@stubbornella we'll gladly accept a pull request.

**Comment by flavorjones** [comment]
Closing, we added this feature in 507f9a1d16cd34f374bea2470bca42585f9078b4. Thanks!
