### ISSUE TITLE
Allow specification of alternate nginx builds

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/staticfile-buildpack#50]
In some cases, it's useful to be able to use a non-standard version of nginx--for example, to use a non-core module or fork with extra functionality. I ran into this recently on a project where I wanted to use some functions from the `set_misc` module.

I wound up rebuilding nginx with the extensions I wanted and adding a check to `compile` to look for an `nginx.tgz` file in the app directory, and use that file instead of downloading if it exists--see https://github.com/jmcarp/staticfile-buildpack/commit/e1a77e17058f020bf8727fd292bcc20cd7d4a8bc. But maybe there's a more elegant way to handle this. I'd be happy to write up a patch if folks are interested in exposing this kind of option.

**Comment by flavorjones** [comment]
Hi, @jmcarp!

Thanks for requesting this feature. I'm curious what extensions you're using? I'd like to better understand the problems you're solving.

The staticfile-buildpack is intentionally very minimal, so clearly some extensibility would be nice to have. I'm not sure I'd accept a PR that allows people to ship their own nginx executable, though -- as that's what the binary-buildpack is intended to do.

**Comment by jmcarp** [comment]
For my specific use case, I'm looking to use a few helpers from nginx `set_misc` module--specifically, I want to sign a subrequest using the included `set_hmac_sha1` directive. Example code here: https://github.com/18F/fec-proxy/blob/hmac/nginx.conf#L53-L55. For now, I'm using a fork of this buildpack that links to a prebuilt openresty nginx binary. This works fine, but I was hoping for a solution that didn't involve hardcoding the nginx version into the buildpack.

IMO, the basic problem is that third-party nginx modules require rebuilding the binary, so the only way to customize nginx with extra modules is to compile your own--unless the buildpack compiles nginx from source, which seems like a bad idea.

**Comment by flavorjones** [comment]
Hey @jmcarp,

I got a similar request today from a co-worker, @infews, who asked about loading a particular module to do third-party authentication, so great minds think alike and whatnot.

Talking this over with @jtarchie, I think I've arrived at the conclusion that the binary-buildpack (in combination with https://github.com/cloudfoundry/binary-builder) is really what you should be using for this use case.

It's difficult to support the combinatorial explosion of modules that people might want to use (notably, set_misc is a third-party module that's not shipped with nginx), and I'm not sure I want to take that on right now.

The alternative I'm suggesting is to use the same tooling that the Buildpacks team uses to construct your own snowflake nginx binary. Maybe this is just the [rootfs docker container][], or maybe you fork [binary-builder][]; but either way, you're in the drivers seat and can build nginx however you want. And then you can use the binary-buildpack to run that executable, easy peasy.

Thoughts?

**Comment by Dannyzen** [comment]
Hey @jmcarp 
Can this be closed?
