### ISSUE TITLE
Allowed directives on custom nginx.conf

### ISSUE THREAD

**Issue by charyorde** [cloudfoundry/staticfile-buildpack#51]
`ERR 2015/10/11 12:51:50 [emerg] 29#0: "server" directive is not allowed here in /home/vcap/app/nginx/conf/nginx.conf:4`

`ERR 2015/10/11 12:48:50 [emerg] 29#0: "upstream" directive is not allowed here in /home/vcap/app/nginx/conf/nginx.conf:3`

Can you please give examples of allowed directives in a custom nginx.conf?

**Comment by charyorde** [comment]
`ERR 2015/10/11 13:03:49 [emerg] 29#0: "location" directive is not allowed here in /home/vcap/app/nginx/conf/nginx.conf:5`

**Comment by charyorde** [comment]
Seems the entire content at `nginx/conf/nginx` has got to be copied over.

**Comment by flavorjones** [comment]
Hi @charyorde,

Can you please explain what you're trying to do, so that we may recommend an implementation to help you achieve your goal?

**Comment by charyorde** [comment]
App1, App2, App3 require a gateway that performs metrics, rate limiting, auth and proxying. staticfile-buildpack can only perform proxying. So during configuration, I was getting above errors because I only placed the upstream and server directives in my custom nginx.conf. What the buildpack desires is to fully replace the content of `nginx/conf/nginx.conf` in a custom `nginx.conf`.

However, I'd have loved if the staticfile-buildpack can be merged into all the CF buildpacks. For example, I could have been able to implement a fully featured gateway in a single NodeJS app only if the Node buildpack has staticfile-buildpack features built-in.
