### ISSUE TITLE
how to force https

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/staticfile-buildpack#55]
I noticed that all my apps using this buildpack default to `http`. I saw in the `nginx.conf` that there's a way to force `https` using an ENV variable called `FORCE_HTTPS`. I set that variable in my manifest file using
```yml
env:
  FORCE_HTTPS: true
```
but the apps still default to http. Am I doing something wrong? Can you please document this feature?

**Comment by jtarchie** [comment]
@mastertinner, are you not seeing traffic 301 redirect to HTTPs?

This is an undocumented feature as some deployed CF environment's router don't support HTTPs.

What environment are you deploying to?

* cf-release version
* buildpack version

**Comment by mastertinner** [comment]
[http://comstrap.scapp.io](http://comstrap.scapp.io) is one of my apps and, as you can see, it doesn't forward to https.
The logs when I'm trying to access my app via the browser are:
```
2015-11-24T15:53:30.44+0100 [App/1]      OUT 195.65.130.2 - - - [24/Nov/2015:14:53:30 +0000] "GET / HTTP/1.1" 200 8833
2015-11-24T15:53:30.44+0100 [RTR/1]      OUT comstrap.scapp.io - [24/11/2015:14:53:30 +0000] "GET / HTTP/1.1" 200 0 8820 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7" 195.65.130.2:52535 x_forwarded_for:"-" x_forwarded_proto:"-" vcap_request_id:8c204f85-0109-4ad3-7f00-1100d9c07cf8 response_time:0.002878341 app_id:107c9f7c-7e7e-41dc-b5f4-a06010865179
```

My problem might occur because of the `x_forwarded_proto:"-"` for which there's an `if`-statement in the `nginx.conf`.

I'm running the `217` cf-release and version `1.2.3` of the buildpack.

**Comment by jtarchie** [comment]
@mastertinner this was an undocumented feature and left unsupported, sorry. I'll talk with our PM about the priority of enabling this.

In the short term, you can provide your own [nginx.conf](https://github.com/cloudfoundry/staticfile-buildpack#advanced-nginx-configuration) to correct this problem. Copy the buidlpack's `nginx.conf` into your app and update to support this feature.

Let us know if that work's for you.

**Comment by flavorjones** [comment]
This looks like it never worked properly, I'll prioritize work on it.

**Comment by ceefour** [comment]
Not working on IBM Bluemix. makes browser goes into infinite redirect loop.

**Comment by flavorjones** [comment]
@ceefour Can you kindly open a new issue which completely describes your problem? Thank you!
