### ISSUE TITLE
Add "gzip_vary on;" to nginx.conf

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/staticfile-buildpack#59]
I think we should add the line `gzip_vary on;` to the `nginx.conf` file. It is recommended here: https://www.maxcdn.com/blog/accept-encoding-its-vary-important/ and can bring performance improvements.

**Comment by Dannyzen** [comment]
@mastertinner Thanks for putting an issue in. The team will discuss your proposal this week. In the interim, please feel free to use nginx.conf in the root folder as you wish.

**Comment by mastertinner** [comment]
@Dannyzen, thanks for letting me know. I am using a custom `nginx.conf` but I think it's something that would make sense to put into default `nginx.conf`. I'm looking forward to hearing about your decision.

**Comment by Dannyzen** [comment]
Hey @mastertinner outside of the blog post you linked, what problem does this solve? What performance metrics can you share with us?

**Comment by flavorjones** [comment]
@mastertinner Can you help us understand why you closed this issue?
