### ISSUE TITLE
How do i edit the nginx.conf using this buildpack ?

### ISSUE THREAD

**Issue by marshell08** [cloudfoundry/staticfile-buildpack#6]
I am not sure How do i edit the nginx.conf file ? Should i place this file in the root directory of my project and push it  ?

I am trying to setup nginx proxy and route all requests through it

**Comment by jtarchie** [comment]
@sdeleuze this feature was added in f49087166c30b04aeb8acd427cee9eb4d6e5d3f0. We are closing issue.

**Comment by Freyert** [comment]
Hate to comment in a closed issue, but am having some trouble with the customization. When I place `nginx.conf` in the _root_ folder specified in `Staticfile` it causes my application to crash. My theory is that it doesn't run this file through the same ERB parsing as the original `nginx.conf`. Can anyone verify that or am I just not doing this correctly.

**Comment by Freyert** [comment]
Looks like I had some invisible error somewhere! Working great, love this project.

**Comment by toolness** [comment]
By the way, the commit referred to above was reverted in 2082dafa5c37468e706bb777aa109ac1de2c9601, but the conversation at the bottom of that commit indicates that the documentation was moved over to http://docs.cloudfoundry.org/buildpacks/staticfile/index.html.

So the feature isn't gone, the documentation on it has just moved to a more centralized place!
