### ISSUE TITLE
Enable SSI (opt-in)

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/staticfile-buildpack#63]
Our users would like to have the ability to enable SSI support in nginx.conf (http://nginx.org/en/docs/http/ngx_http_ssi_module.html). It's a core nginx module so all it takes is a `ssi on;` directive in nginx.conf. 

We were thinking to leave it off by default, and using the same mechanism used by directory index to enable it.

**Comment by Dannyzen** [comment]
@CAFxX Do you have any information that you can share with us around their use case to give us context around why they want to enable SSI support?

**Comment by CAFxX** [comment]
Until now my understanding is that they have a bunch of legacy servers serving static content that uses SSI include directives. Load on the servers is very spiky and administrative burden is high, would love to migrate to our internal CF.
They could supply their own nginx.conf, but that requires more work.

**Comment by Dannyzen** [comment]
@CAFxX Do you happen to have any additional use cases?

**Comment by CAFxX** [comment]
Not really, talked with multiple teams and the primary reason for requiring SSI to migrate is because their legacy sites depend on it (it was a common technology in the company until a while back).

**Comment by Dannyzen** [comment]
@CAFxX we've included this feature in https://github.com/cloudfoundry/staticfile-buildpack/commit/8a93ee948431c8f21c11294974783022f0a20cf4. It should be in the develop branch. If you have any additional comments please let us know. If you're all set, please close this issue.

**Comment by Dannyzen** [comment]
@CAFxX We've included this in our latest release. Thanks again for your input.

**Comment by CAFxX** [comment]
Thanks!
