### ISSUE TITLE
Default configuration uses an unnecessarily large amount of diskspace

### ISSUE THREAD

**Issue by flavorjones** [cloudfoundry/staticfile-buildpack#65]
Currently the staticfile-buildpack, during staging, will **copy** files from the declared root directory into a `public/` subdirectory:

> https://github.com/cloudfoundry/staticfile-buildpack/blob/master/bin/compile#L44-L49

Unless my root directory is already `public/`, this results in a doubling of the diskspace used by the application bits.

For example, if I have the following application:

```
Staticfile # specifying `public/` as my root directory
public/data # a 2MB file containing random bits
```

then the droplet is 4.4MB, as seen in the staging log output:

```
Staging complete
Uploading droplet, build artifacts cache...
Uploading droplet...
Uploading build artifacts cache...
Uploaded build artifacts cache (129B)
Uploaded droplet (4.4M)
```

If I have the same data file in this application:

```
Staticfile # not declaring a root directory
data # a 2MB file containing random bits
```

then the droplet is 6.3MB:

```
Staging complete
Uploading droplet, build artifacts cache...
Uploading droplet...
Uploading build artifacts cache...
Uploaded build artifacts cache (131B)
Uploaded droplet (6.3M)
```

This double-counting of application bits counts against my disk quota, which is undesired.

I don't have a proposed solution at this time, but would like to generate discussion.

**Comment by jtarchie** [comment]
Looks like this my cover the case.

http://askubuntu.com/questions/91740/how-to-move-all-files-in-current-folder-to-subfolder

**Comment by RochesterinNYC** [comment]
This issue has been resolved by the completion of the following [story](https://www.pivotaltracker.com/n/projects/1042066/stories/112908945). Related commits are referenced in the story. Thanks for bringing this to our attention @flavorjones
