### ISSUE TITLE
access_log syslog:server=xxx in nginx.conf not working

### ISSUE THREAD

**Issue by roma929** [cloudfoundry/staticfile-buildpack#67]
I'm forwarding Nginx access log to Logentries. I added this line to nginx.config and push to Bluemix but doesn't work. Here is the line: 

"access_log syslog:server=xxx,logentries.com:xxxx cloudfoundry;"

Is this supported? It works on my local machine, Macbook and Ubuntu.

**Comment by jtarchie** [comment]
@roma929, the nginx that we support does have `syslog` support for logging. Please contact your Bluemix (your cf provider) for help debugging the problem.
