### ISSUE TITLE
how to use this buildpack in eclipse

### ISSUE THREAD

**Issue by imleihuang** [cloudfoundry/staticfile-buildpack#70]
I have read how to install this buildpack in cloud. but I have the other question, hope somebody can answer it. 

I write AngularJS code using Webstorm IDE. I just want to push this AngularJs Web Application in cloud foundry. The following steps should be done.
1. install staticfile buildpack firstly in cloud.
2. push AngularJS application to clound. 

Is that right??

My Question.
How can I use Eclipse or Webstorm to deploy Angular JS  using staticfile buildpack.

can someone give some example? 

Thanks a lot

LH

**Comment by davidjahn** [comment]
Hi Lei,

Are you trying to push an app to [PWS](http://run.pivotal.io/) or another cloud foundry deployment?

Webstorm and Eclipse are not related to cloud foundry. You push apps with the [cli tool](https://github.com/cloudfoundry/cli).

If you have logged into cloud foundry with
```
cf api <ip address of your cloud foundry>
cf login
```
then you should be able to push a static application by making a zero-byte `Staticfile` file in the root of your app, then doing `cf push`.

**Comment by RochesterinNYC** [comment]
@imleihuang closing this issue due to lack of feedback. Please let us know if you need further assistance.
