### ISSUE TITLE
spurious error messages when pushing a project without a Staticfile

### ISSUE THREAD

**Issue by flavorjones** [cloudfoundry/staticfile-buildpack#73]
What version of Cloud Foundry are you using?

latest

What version of the buildpack you are using?

v1.3.6

If you were attempting to accomplish a task, what was it you were attempting to do?

Pushing a static site using `-b staticfile_buildpack` when the directory doesn't contains a `Staticfile` file

What did you expect to happen?

I expected to see no errors

What was the actual behavior?

Following output contains error messages from failed `grep` commands:

```
Downloading staticfile_buildpack...
Downloaded staticfile_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (63.9K)
Staging...
-------> Buildpack version 1.3.6
Downloaded [file:///tmp/buildpacks/a0196007b227496ea71bcdcdd0e4f798/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_nginx_nginx-1.9.14-linux-x64.tgz]
grep: Staticfile: No such file or directory
-----> Using root folder
-----> Copying project files into public/
-----> Setting up nginx
grep: Staticfile: No such file or directory
grep: Staticfile: No such file or directory
Exit status 0
Staging complete
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (108B)
Uploaded droplet (2.5M)
Uploading complete

1 of 1 instances running
```

Please confirm where necessary:
* [x] I have included a log output 
* [x] My log includes an error message 
* [x] I have included steps for reproduction

**Comment by Dannyzen** [comment]
@flavorjones thanks for putting in an issue. I can reproduce this as well, we'll prioritize a fix.

**Comment by RochesterinNYC** [comment]
This issue has been resolved by https://github.com/cloudfoundry/staticfile-buildpack/commit/9f1f8f39f20fa7e4e00cb3caf5a805a7ffb77648. Thanks for pointing out the issue @flavorjones
