### ISSUE TITLE
Compile the authentication module with nginx to enable basic auth against LDAP/AD

### ISSUE THREAD

**Issue by eddiewebb** [cloudfoundry/staticfile-buildpack#75]
We would like to add authentication modules to nginx.  (ldap-auth)  (i.e. https://github.com/nginxinc/nginx-ldap-auth or https://github.com/kvspb/nginx-auth-ldap)

We have a growing need to force authentication for static sites, and in apache I would use **user-binded** auth  (we do not want to provide a system ID to bind because that introduces sensitive credentials to source),  looks like nginx needs custom modules for that.

The use case is that inside our large corporate environment all sites must require authentication.  We are not so concerned with authorization, though that would be a nice perk.  We just need to ensure that whoever is trying to access the site is a valid employee with active credentials, and not one of the many vendors and visitors with access to a LAN port.

I threw this out to the buildpack community on Slack who suggested I log this enhancement request.  Please let me know if details below are not sufficient.
https://cloudfoundry.slack.com/archives/buildpacks/p1461159231000083 

What version of Cloud Foundry are you using?

What version of the buildpack you are using?
1.3.6

If you were attempting to accomplish a task, what was it you were attempting to do?
Enable basic auth to bind against LDAP with user provided credentials.

What did you expect to happen?

1. Able to configure LDAP endpoint, uid, and LDAP tree needed to bind as user and validate password.
1. User attempts to view site using static build pack
1. User is prompted for enterprise ID and password
1. User credentials are used in attempt to bind to LDAP/AD server
1. Only if bind is successful can user view site.

What was the actual behavior?
Not available.

Please confirm where necessary:
* [ ] I have included a log output 
* [ ] My log includes an error message 
* [ ] I have included steps for reproduction

N/A - new feature request, not a bug.

**Comment by flavorjones** [comment]
Is there a reason you wouldn't prefer to use a route service to perform authentication instead of building it into the nginx configuration?

> http://docs.cloudfoundry.org/services/route-services.html

I think our logic was that basic auth that doesn't require integration with outside services was a reasonable thing to support in the buildpack; but introducing external integrations is, in my opinion, perhaps a function that's better served elsewhere in the system.

A route service would be more easily testable and reusable. Have you considered it as an alternative?

**Comment by eddiewebb** [comment]
Thanks @flavorjones - I'm circulating that idea with the team, but cursory glance does raise one major concern for us around secrets management.

```
properties:
 router:
   route_services_secret: YOUR-SECRET-PASSPHRASE
```

We would need to developers to encrypt that before checking into our CD pipelines, and then decrypt that portion of the manifest as part of the automated push.    For dynamic buildpacks we use libraries in the running app to decrypt on the fly with user provided services that stage the appropriate key.

Anyway, I'll see what others on the team think.

**Comment by eddiewebb** [comment]
Got some education after talking with the team. We are waiting to move to 1.7 but otherwise the route service seems like a viable option.  Thanks @flavorjones !
