### ISSUE TITLE
link to the documentation

### ISSUE THREAD

**Issue by afeld** [cloudfoundry/staticfile-buildpack#76]
Would be helpful for the top of the repository and/or the README to link to the docs:

https://docs.cloudfoundry.org/buildpacks/staticfile/index.html

Thanks!

**Comment by RochesterinNYC** [comment]
The documentation at the top [Using the Buildpack](https://github.com/cloudfoundry/staticfile-buildpack#using-the-buildpack) section includes that link.

**Comment by afeld** [comment]
Ah sorry, missed that! Thoughts about adding it as the repository `homepage` (the URL next to the repository description) to make it even more visible?

**Comment by Dannyzen** [comment]
I've made a change to the readme to make it clearer. Thanks for the feedback!
