### ISSUE TITLE
RFC: Ability to include an nginx config

### ISSUE THREAD

**Issue by Dannyzen** [cloudfoundry/staticfile-buildpack#77]
The current functionality of the staticfile-buildpack is to overwrite the provided nginx.conf if a user-provided one exists. The Buildpacks team is curious if users are interested in the ability to add a non-destructive nginx-additions.conf config file, which, if provided, would exist additively on top of the current config.

If you find this idea compelling, please comment on the issue as we'd like to talk to you a bit more about the expected functionality.

Thanks for your time

**Comment by flavorjones** [comment]
Currently the `nginx.conf` file provided in the buildpack is structured with several levels of nesting:

```
<global>

http {
  ...
  server {
    ...
    location / {
      ...
    }   
  }
}
```

So ideally respondents (if any) to this issue should please indicate specifically where their desired configuration would be injected in this structure.

**Comment by youngm** [comment]
We have a request for this type of functionality.  In our case our user wanted to customize the cache control.  Here is an example snippet if it helps:

```
  server {
    listen 8080;
    server_name localhost;

    # Cache these
    location ~* \.(?:css|js|jpg|gif)$ {
      root /home/vcap/app/public;
      index index.html index.htm Default.htm;
      expires 8h;                                 # Cache for 8 hours
    }

    # Default for all other files (don't cache)
    location / {
      root /home/vcap/app/public;
      index index.html index.htm Default.htm;
      expires -1;                                 # Turn off caching
    }

  }
```

**Comment by dkoper** [comment]
The PubTools team uses the static-buildpack with a custom nginx.conf to add redirection rules like http://cli.cloudfoundry.org -> http://cli.cloudfoundry.org/en-US/cf/ and return custom 404 not found pages for urls with typos like http://cli.cloudfoundry.org/en-US/cf/command-with-typo. 

A concern I had with the current approach is that we had to copy the whole nginx.conf file, potentially missing out on improvements and security fixes made to the original one in subsequent buildpack updates.

So we would definitely prefer an nginx-additions.conf approach!

**Comment by nota-ja** [comment]
We will welcome this feature because it wil be easier to explain how to customize nginx.conf.

Now we should explain to our customer: "Here is the default configuration file. Please copy it to your local  first, then rewrite it."

This explanation will be easier when the feature is introduced, just like: "Please write your customized configuration item." Though a customer should of course mind what is the default, it is easy to understand.

We also agree what @dkoper said about improvement and security. This feature will make us avoid
using obsolete nginx.conf.

**Comment by flavorjones** [comment]
@nota-ja Can you please provide specific examples of configurations you'd like to be able to make through this method? As I mentioned in my [comment above](https://github.com/cloudfoundry/staticfile-buildpack/issues/77#issuecomment-227490492), there are many different places where configuration can be injected and we'd like to understand *specific* use cases.

**Comment by CAFxX** [comment]
I'm all for it as long as we maintain the current ability to override the whole nginx.conf

**Comment by Dannyzen** [comment]
Due to the complexity of the nested nature of `nginx.conf` we've concluded that implementing this feature may cause more problems than joy. Each use case that this proposal attempts to solve can be satisfied by [overriding the default `nginx.conf`](http://docs.cloudfoundry.org/buildpacks/staticfile/#custom_nginx_configuration). 

Specifically, questions have come up around the location in which configuration may be injected. For if  configuration can be injected into a specific section and that section is removed or modified, unexpected conflicts can occur. 

We're committed to making using the staticfile-buildpack a great experience, if you have needs that are not currently fulfilled, please help us help you by putting in an issue.
