### ISSUE TITLE
Enabling `FORCE_HTTPS` in Bluemix + CloudFlare (Flexible) triggers infinite redirect loop

### ISSUE THREAD

**Issue by ceefour** [cloudfoundry/staticfile-buildpack#80]
Originally reported as https://github.com/cloudfoundry/staticfile-buildpack/issues/55#issuecomment-239027957

## What version of Cloud Foundry are you using?

IBM Bluemix. cf version 6.21.0+dff2cf8-2016-07-27

## What version of the buildpack you are using?

```
-------> Buildpack version 1.3.6
Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/d7214a80-2e86-49ea-987d-c06f376ff950_de3bedc191535d4743e0b391458736b183f9209b/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_nginx_nginx-1.9.14-linux-x64.tgz]
```

## If you were attempting to accomplish a task, what was it you were attempting to do?

Redirect http -> https

## What did you expect to happen?

1. For HTTP connection (only!), redirect to HTTPS. By the way, Bluemix always connects to app as HTTP
2. For HTTPS, stay that way. By the way, CloudFlare SSL can be configured to be Flexible, Full, Full (Strict), see https://support.cloudflare.com/hc/en-us/articles/200170516-How-do-I-add-SSL-to-my-site-
3. If I comment the FORCE_HTTPS in manifest, it will no longer provide https redirection.

## What was the actual behavior?

1.  Even if I comment `FORCE_HTTPS: true` in manifest, or I set `FORCE_HTTPS: false`, the https redirection is still being done.

2. Server always issues a redirect, even if browser accesses via https.

Server:

```
App/0162.158.162.29, 108.168.250.152 - - - [11/Aug/2016:03:31:49 +0000] "GET / HTTP/1.1" 301 1782016-08-11T10:31:49.741+0700
RTR/1eragano.com - [11/08/2016:03:31:49.735 +0000] "GET / HTTP/1.1" 301 0 178 "-" "curl/7.49.1" 108.168.250.152:19570 x_forwarded_for:"162.158.162.29" x_forwarded_proto:"http" vcap_request_id:6fe316d2-1b63-4f98-67c5-b76c1bef074a response_time:0.004735874 app_id:3eb4af31-6082-42db-b363-d9709803d8bc x_global_transaction_id:"3058027583"
```

Client:

```
$ curl  -v https://www.eragano.com/
* timeout on name lookup is not supported
*   Trying 104.28.12.205...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to www.eragano.com (104.28.12.205) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\Users\ceefour\.lein\bin\curl-ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3424 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [149 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni76253.cloudflaressl.com
*  start date: Aug  9 00:00:00 2016 GMT
*  expire date: Feb 12 23:59:59 2017 GMT
*  subjectAltName: host "www.eragano.com" matched cert's "*.eragano.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* TCP_NODELAY set
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x68ce90)
} [5 bytes data]
> GET / HTTP/1.1
> Host: www.eragano.com
> User-Agent: curl/7.49.1
> Accept: */*
>
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
} [5 bytes data]
* HTTP 1.0, assume close after body
< HTTP/2 301
< date: Thu, 11 Aug 2016 03:29:33 GMT
< content-type: text/html
< set-cookie: __cfduid=dafc17cc9e01e7dc926ac8617cfe4fa531470886173; expires=Fri, 11-Aug-17 03:29:33 GMT; path=/; domain=.eragano.com; HttpOnly
< x-backside-transport: OK OK
< location: https://www.eragano.com/
< x-vcap-request-id: 558316fa-7ce6-4fd3-650e-aa88d58a1dbe
< x-client-ip: 162.158.163.13
< x-global-transaction-id: 2354409361
< server: cloudflare-nginx
< cf-ray: 2d089a988c9e1123-SIN
<
{ [178 bytes data]
100   178    0   178    0     0    227      0 --:--:-- --:--:-- --:--:--   227<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

* Closing connection 0
} [5 bytes data]
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
```

## Potential Clue

It seems CloudFlare by default (Flexible) always proxies using HTTP, even if browser is HTTPS.
While CloudFlare Full proxies using HTTPS if browser HTTPS, and using HTTP if browser is HTTP.

However, I still don't know why `FORCE_HTTPS` switch can't be disabled after enabled once.
With `FORCE_HTTPS: false`, even when accessing the mybluemix.net subdomain directly, without CloudFlare, https redirection still performed:

```
$ curl -v http://eragano-com.mybluemix.net
* Rebuilt URL to: http://eragano-com.mybluemix.net/
* timeout on name lookup is not supported
*   Trying 169.54.245.69...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to eragano-com.mybluemix.net (169.54.245.69) port 80 (#0)
> GET / HTTP/1.1
> Host: eragano-com.mybluemix.net
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< X-Backside-Transport: OK OK
< Connection: Keep-Alive
< Transfer-Encoding: chunked
< Content-Type: text/html
< Date: Thu, 11 Aug 2016 04:03:40 GMT
< Location: https://eragano-com.mybluemix.net/
< Server: nginx
< X-Global-Transaction-ID: 1613537793
<
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{ [189 bytes data]
100   178    0   178    0     0    189      0 --:--:-- --:--:-- --:--:--   207<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

* Connection #0 to host eragano-com.mybluemix.net left intact
```

## Please confirm where necessary:

* [v] I have included a log output 
* [v] My log includes an error message 
* [v] I have included steps for reproduction

**Comment by ceefour** [comment]
I think I know why disabling `FORCE_HTTPS` did not take effect:

![image](https://cloud.githubusercontent.com/assets/24123/17578859/b9f905ba-5fb8-11e6-89cd-7e575dec4930.png)

Bluemix sets this in the app's environment variable, and it is persistent.

However, there's no way to remove the environment variable using `manifest.yml`.
Commenting the `manifest.yml` is treated as "no-op". And using:

```yaml
env:
  FORCE_HTTPS:
```

is (null) not allowed.

**Comment by RochesterinNYC** [comment]
Hi @ceefour, interesting problem! We've prioritized a bug investigation/fix here: https://www.pivotaltracker.com/story/show/128127631

We've also included a task to add `FORCE_HTTPS` to our docs.

**Comment by RochesterinNYC** [comment]
@ceefour after doing a more explicit read-through of your issue, we're a bit confused about the current state of your issue/app. Is the redirect problem resolved/an issue with Cloudflare?

Is the only action item here to add notes about `FORCE_HTTPS` and how the value you assign for that environment variable does not matter (true, false, etc.) to the Cloud Foundry docs?

As a side note, the reason that commenting out `FORCE_HTTPS` in the manifest does not delete that value is because the Cloud Controller has no direct connection or relation to your app manifest. Your app manifest is used by the CF CLI to know what values to set for things when the CLI talks to the CC API.

For example, if you have a manifest:
```
env:
  FORCE_HTTPS: true
  OTHER_VAR: 1
```

and you push your app, the CF CLI parses the manifest and then tells CC API that this app needs to set `FORCE_HTTPS` to true and `OTHER_VAR` to 1. 

Then, if you alter your manifest to:

```
env:
  OTHER_VAR: 1
```

and repush, the CF CLI tells CC API this app needs to set `OTHER_VAR` to 1. The CF CLI has no state and does not know anything about the `FORCE_HTTPS` env var you removed from your manifest and will not give any info about it to the CC API on this push.

**Comment by ceefour** [comment]
Yes, there were 3 issues that I wasn't aware how each of them works so
complicated the matter:

1. `FORCE_HTTPS: false` is still "true"
2. No way to remove setting in manifest.yml
3. CloudFlare's HTTP->HTTPS support (which results in redirect loop when
FORCE_HTTPS is set even to "false")

For staticfile-buildpack you need to document case 1 better.

For case 2 I'd argue there's need to remove a variable from manifest.yml,
but it is CloudFoundry's spec not staticfile-buildpack. But it is a major
problem as there's currently no way to do it purely from manifest.yml ie
you have no "reproducible" build.

For case 3 it's out of scope, but CloudFlare does this convenience and I
believe others too, so I think it's good to put a warning on this on your
documentation.

**Comment by RochesterinNYC** [comment]
For things related to Cloud Foundry as a whole, it might be worth posting to the cf-dev mailing list: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/

It's a good place for overarching discussions, questions, and proposals about Cloud Foundry, which is where something like the concern about environment variables and `manifest.yml` would go.

Thanks for the feedback on the docs additions. We'll update the docs accordingly.
