### ISSUE TITLE
Http/2 support

### ISSUE THREAD

**Issue by Wykks** [cloudfoundry/staticfile-buildpack#81]
Is there any way to use http/2 with this, since nginx support it ?

Thanks !

**Comment by jchesterpivotal** [comment]
Hi @Wykks 

We looked into it a bit and we drew a different conclusion. Nginx does not support HTTP/2 "out of the box". It would require us to compile in a custom module, which is currently marked by the developers as "experimental".

Nginx compiles to a single binary, so we'd be imposing that experimental code on *everyone* who uses the staticfile buildpack.

Until Nginx fold HTTP/2 into the mainline, or mark the HTTP/2 module as being production-ready, we don't think we can do this. Closing.

**Comment by danielraad** [comment]
This module is no longer marked as experimental:

http://hg.nginx.org/nginx.org/rev/88228d493640

Would it be possible to reopen this issue?

**Comment by sclevine** [comment]
I'll re-open this, especially since NGINX supports dynamic modules now.

**Comment by dgodd** [comment]
@danielraad I'm wondering what your use case is for this? For most CF installations, gorouter will live in front of the app and terminate using HTTP/1.x, and proxy to the app over HTTP/1.x (https://github.com/cloudfoundry/gorouter#http2-support) so in that usecase adding HTTP/2.0 to the app container will not be relevant.

Is there a different usecase that I'm not thinking through?

**Comment by danielraad** [comment]
@dgodd that was indeed the use case that I was interested in, I didn't realize that gorouter does not support http/2 yet.
