### ISSUE TITLE
Mail module missing

### ISSUE THREAD

**Issue by navaneethant** [cloudfoundry/staticfile-buildpack#85]
I am using latest code. I was trying to use mail proxy in nginx but I am getting error pushing the app. Mail directives is missing. Let me know how to fix this.

**Comment by flavorjones** [comment]
Hello! Thanks for asking this question.

We're not currently compiling the mail modules into the nginx provided in the staticfile buildpack. You can see which modules we're compiling here:

https://github.com/cloudfoundry/binary-builder/blob/master/recipe/nginx.rb

Can you help us understand what you're attempting to do? We may be able to offer advice or assistance. When we better understand your requirements we can also consider whether to make changes to the buildpack to accommodate the use case.

Thank you!

**Comment by sesmith177** [comment]
Hello @navaneethant,

Any thoughts on the feedback from @flavorjones ?

**Comment by RochesterinNYC** [comment]
Hi @navaneethant, we're closing this issue due to lack of response. Please reopen the issue with more info/a response if you want to continue discussion on this.
