### ISSUE TITLE
Add LUA to the buildpack

### ISSUE THREAD

**Issue by JelteMX** [cloudfoundry/staticfile-buildpack#86]
Feature request:

I have been working with the staticfile-buildpack for a while and I have a question/feature request. I am trying to do URL rewrites, to make sure my urls are always lowercase. I came across [this tutorial](https://dodwell.us/rewrite-uri-to-lowercase-using-nginxperl-nginxlua-or-apache.html) to do it with Perl/LUA. As LUA is faster the latter is preferred.

Can this be added to the buildpack? (Or, in the case that's not going to happen, give thoughts on how to do this with an other buildpack)

**Comment by RochesterinNYC** [comment]
Currently, the only way to handle this use case would be to:

- fork the buildpack and change the `bin/compile` script to install LUA or Perl (via `curl` and installation) or something similar. Note that the `vcap` user running `bin/compile` does not have `sudo` privileges so `apt-get install lua` will not work.
- fork the buildpack and vendor in a packaged LUA binary for use in the cached version of the buildpack. Example of [how we vendor in nginx] (https://github.com/cloudfoundry/staticfile-buildpack/blob/master/manifest.yml#L18-L23), [how we get that vendored file during staging](https://github.com/cloudfoundry/staticfile-buildpack/blob/master/bin/compile#L21-L22), and [how we untar and setup nginx](https://github.com/cloudfoundry/staticfile-buildpack/blob/master/bin/compile#L69-L112). This blog post about custom buildpacks might be helpful as well: http://engineering.pivotal.io/post/creating-a-custom-buildpack/
- Add LUA or Perl to a custom rootfs that you can generate using stacks: https://github.com/cloudfoundry/stacks

The Buildpacks team is undergoing a track of work to add multi buildpack support, which would cover this use case. You could stage the staticfile buildpack after staging a perl buildpack or lua buildpack and both perl/LUA and nginx would be available on the end app droplet. During the staticfile buildpack staging, perl or LUA would be available as well.

**Comment by jchesterpivotal** [comment]
As a totally irrelevant nitpick, it's "Lua", not "LUA". It's not an acronym, it's the Portuguese word for "Moon".

**Comment by JelteMX** [comment]
Thanks @RochesterinNYC for the suggestions, I am going to look into those 👍

**Comment by sesmith177** [comment]
@JelteMX have you been able to follow @RochesterinNYC 's suggestions?

**Comment by JelteMX** [comment]
Nope, not yet. I need more time to dig into it. I have zero experience with creating buildpacks, but I am a quick learner. Already made some adjustment to a project I am working on ([Mendix docs](https://github.com/mendix/docs)) where we do redirects, but I need to get the url rewriting fixed soon.

**Comment by athornton2012** [comment]
@JelteMX any issues with forking the buildpack?

**Comment by JelteMX** [comment]
Well due to time-pressure I didn't get around to do it. We found a (not ideal) workaround, but I am still going to do it (probably end of this week/next week)

**Comment by athornton2012** [comment]
@JelteMX On second thought, Perl is already included in the rootfs. Is there any reason you wouldn't want to use Perl?

**Comment by JelteMX** [comment]
Wait, what? Can I use Perl here? That changes things. I'll have a look at it later on. If I can use this, I don't need to use Lua (although, as for what I have read, Lua is slightly faster. Faster is better on a high-traffic website)

**Comment by sclevine** [comment]
Closing this for now as we have no plans to add Lua to the buildpack. Feel free to open new issues for future reports, suggestions, or questions.

**Comment by techtenk** [comment]
I'm also interested in enabling Lua, but perhaps Perl will work for my purposes. Is  ngx_http_perl_module enabled by default in this buildpack? How would I tell, and how would I enable it if not?
