### ISSUE TITLE
Support CORS headers

### ISSUE THREAD

**Issue by geoffwa** [cloudfoundry/staticfile-buildpack#89]
It'd be awesome if the buildpack would support CORS headers.

Often when building a webapp there's a need to make a mock version of a particular API to fetch information from. For read-only APIs this can be done easily by nesting JSON files in directories and deploying this to some sort of static hosting service. This is a bit simpler than write a tiny express or sinatra app to server static content with the requisite CORS headers.

I imagine something along the lines of:

`ENABLE_CORS=<Access-Control-Allow-Origin header value>`

which would dump something like the following into the nginx.conf:

```
add_header 'Access-Control-Allow-Origin' '$ENABLE_CORS'
add_header 'Access-Control-Allow-Methods' 'OPTIONS, HEAD, GET'
add_header 'Access-Control-Allow-Headers' 'Origin,Referer,User-Agent,X-Requested-With,Date,Keep-Alive,Cache-Control,If-Modified-Since,If-None-Match,Range,Accept-Charset,Accept-Encoding'
```

(I just shotgunned a bunch of headers into `Access-Control-Allow-Headers`, it's not an exhaustive list)

**Comment by sclevine** [comment]
Story to add Staticfile option: https://www.pivotaltracker.com/story/show/136370663

**Comment by sclevine** [comment]
We've decided not to include this feature in favor of the new `location_include` Staticfile option that allows you to specify a file containing arbitrary NGINX configuration. Check out the example app here: https://github.com/cloudfoundry/staticfile-buildpack/tree/master/cf_spec/fixtures/include_headers

**Comment by jagadish-kb** [comment]
Example App URL should be : https://github.com/cloudfoundry/staticfile-buildpack/tree/2187a7f8c77aac27208de834c9e683fc9ac165dd/fixtures/include_headers_dist
