### ISSUE TITLE
Support for Environment Variables

### ISSUE THREAD

**Issue by felipeg48** [cloudfoundry/staticfile-buildpack#93]
Support for Environment Variables

Problem:
Most of the Web applications come integrated with
its presentation layer. For example, to create an e-commerce
site is necessary to add not only the server side logic, but also the front-end, HTML, CSS, JavaScript and more.

If we want to separate these layers and use a pure presentation app, like an AngularJS application that can talk to some Rest API, we need either use: 
- Services (Manage or User Provided), or
- Environment Variables (OS, VCAP_SERVICES, custom, etc)
so its easy for the application to know the URL.

Solution:
Provide a way to tell JavaScript to use the Environment
variables.

Suggestions:
I actually create some notes of how to build a custom staticfile_buildpack
that allows your JavaScript app to access the VCAP_SERVICES variable, see [here](https://github.com/felipeg48/cloud-foundry-notes/blob/master/custom-buildpacks/js-buildpack.adoc)

I don't know if this could be possible to add it?
If not, what would be the reason?

**Comment by sclevine** [comment]
Here are a few reasons why we wouldn't want to support this in the buildpack:
1. **Environment variables very often contain sensitive credentials.** This is a pattern that CF enforces via the `VCAP_SERVICES` environment variable. We also encourage app authors to supply their app with other kinds of credentials (for example, API keys) via custom environment variables. Pushing these credentials to the client without any validation or filtering would mean leaking service credentials to every user of the app.

2. **The purpose of the staticfile buildpack is to serve static content, not web applications.** If you want to write an interactive web application in Angular that makes use of services, you should use a backend language technology to mediate access to those services.

**Comment by felipeg48** [comment]
Thanks Stephen makes sense, thanks for the response, and we can close this.

Thanks again

**Comment by cah-andrewfitzgerald** [comment]
I asked a question about this in the slack #buildpacks channel that @dgodd helped me out with.
We're porting an existing application to cloud foundry that we currently run in an nginx docker container.  We have a couple environment related variables (such as urls/names) that we use to update a `config.js` template via a script containing a couple sed commands.

We run this script once on startup, then start nginx.

It's possible to do something similar in PCF by modifying the start command, but it is unintuitive and that use case is currently undocumented.

So for me the, pcf environment use case would be to provide some sort of templating system within the static build pack to allow environment variables to update specific files on container startup.

**Comment by fljmayer** [comment]
I disagree with the statement **The purpose of the staticfile buildpack is to serve static content, not web applications.**:

A modern single-page webapp (e.g. with Angular) consists solely of static content (`index.html` and JavaScript files) that uses REST endpoints to retrieve all dynamic content. Such a single-page webapp needs some configuration to work in different environments. Using something like Node.js just for some configuration would be overkill.

**Comment by sclevine** [comment]
I agree that there is a balance of functionality that this buildpack should provide to support rich static-content apps that don't involve custom backend logic. I didn't intend to include fully front-end apps in that statement. We are happy to add specific features that support this use case. That said, if you need to make NGINX customizations that are uncommon or involve a significant amount of logic for your front-end app, I would recommend using the (still experimnental) [nginx-buildpack](https://github.com/cloudfoundry/nginx-buildpack) instead. It's difficult for us to support complex changes to nginx.conf and maintain backwards compatibility, and most users of this buildpack are hosting non-interactive content.

If you have specific features you'd like to see, please don't hesitate to open an issue (or a PR!).

However, this particular issue is about exposing `VCAP_SERVICES` to clients. That would introduce a security vulnerability, by sending every user of the site the full credentials to all services bound to the app (ie. all visitors would have full access to the production DB).
