### ISSUE TITLE
Support Cache Control Public Max-Age

### ISSUE THREAD

**Issue by rdy** [cloudfoundry/staticfile-buildpack#94]
I'm looking to leverage in browser caching for static web applications where assets are completely precompiled. I would like some way to specify public cache control headers for assets provided where one could set a far future Max-Age.

The static assets provided already have a hash in their filename so it guarantees the browser will do the right thing. This would help to improve SEO for apps the are already pre-built having a way to set the cache control headers. I found some previous issues that mentioned caching but they were different from what I'm looking for which is strictly for the browser hints.

**Comment by sclevine** [comment]
Sorry for the delayed reply. The next release of the buildpack will allow you to include arbitrary NGINX configuration in the `location /` block. Would this satisfy your use case? See: https://www.pivotaltracker.com/story/show/136370663

If you just need to set a single `Cache-Control: max-age=<seconds>` header on all requests, we could add a `max-age` Staticfile property for this as well.

**Comment by rdy** [comment]
Yea this works for me, I'll look to the next release of the buildpack.

**Comment by sclevine** [comment]
Released in [v1.3.18](https://github.com/cloudfoundry/staticfile-buildpack/releases/tag/v1.3.18).
