### ISSUE TITLE
Support for dynamically loading http_geoip_module

### ISSUE THREAD

**Issue by imravichaudhary** [cloudfoundry/staticfile-buildpack#95]
What version of Cloud Foundry and CF CLI are you using?

**cf version 6.22.2+a95e24c-2016-10-27**
**API version: 2.54.0**

What version of the buildpack you are using?

**1.3.17**

If you were attempting to accomplish a task, what was it you were attempting to do?

**Dynamically Loading NGINX Modules
For example: load_module "modules/ngx_http_geoip_module.so";**

What did you expect to happen?

**To specify a database used to determine the country depending on the client IP address.
like use of geoip_country and geoip_city**

What was the actual behavior?

**"load_module" directive is not allowed**

**Comment by sclevine** [comment]
Can you provide a sample app that reproduces this behavior? It seems like you may be including the `load_module` directive in the wrong place in your custom `nginx.conf` file.

**Comment by imravichaudhary** [comment]
@sclevine Thank you pointing the mistake. I was placing the `load_module` in wrong place.
Though I am not getting the same error but I do need `shared object file` for the module.

I can get the module using `apt-get install nginx-module-geoip` and copy it to the public directory and provide the path to the `load_module` but that seems a dirty way of loading the module.

So, is there a way to install the modules using `manifest.yml` file?

**Comment by sclevine** [comment]
If you're asking about the app `manifest.yml`, then no, there is no way to specify additional NGINX modules there.

If you're asking about the buildpack `manifest.yml`, it may actually be easier to re-build NGINX with the geoip module if you plan to fork the buildpack anyways. See: https://github.com/cloudfoundry/binary-builder/blob/master/recipe/nginx.rb
