### ISSUE TITLE
Request for Dynatrace AppMon agent to be installed using Static Buildpack

### ISSUE THREAD

**Issue by lnguyen2341** [cloudfoundry/staticfile-buildpack#97]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`? PCF v1.8 and CLI 6.23.1

What version of the buildpack you are using?
Static buildpack 1.3.9

If you were attempting to accomplish a task, what was it you were attempting to do?
Would like to have the Dynatrace AppMon agent included in the buildpack.  The goal is to enable the Dynatrace APM to monitor static web apps running on PCF.

What did you expect to happen?
The goal is to enable the Dynatrace APM to monitor static web apps running on PCF.

What was the actual behavior?
Currently, there is no Dynatrace AppMon in the static buildpack.

Please confirm where necessary:
* [ N/A] I have included a log output
* [ N/A] My log includes an error message
* [N/A ] I have included steps for reproduction

**Comment by sclevine** [comment]
Hi @lnguyen2341,

Is the Dynatrace AppMon agent open source? Can you link me to the license and distribution terms?

**Comment by akirasoft** [comment]
@sclevine While the agent is not open-source we have updated the terms and conditions of the agent to allow it to be freely distributed by anyone. We are also foundation sponsors and have a CLA. I am investigating this as well. What I'm trying to wrap my head around here is not just getting the agent injected into nginx (which can be done via manipulating the nginx.conf) but utilizing the buildpack construct to standup a second daemon process that our agent communicates to on the webserver via shared memory. I was able to implement it via the php buildpack here in my fork (https://github.com/akirasoft/php-buildpack/blob/master/extensions/dynatrace/extension.py)

**Comment by sclevine** [comment]
On develop as c64806ac6308edff0c1581e3b20838201dc550b4 -- this will be available in the next release.

**Comment by stipx** [comment]
Basically the Dynatrace OneAgent is a bit different from the AppMon agent. So the integration only covers the SaaS (or also managed) service of Dynatrace. Dynatrace AppMon usually covers a slightly different use case. 
So the integration does not support the AppMon agent. Sorry.
