### ISSUE TITLE
Document where the built nginx artifact comes from

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/staticfile-buildpack#98]
We often receive inquiries from our internal users about how is the nginx in the staticfile bp built (e.g. which build flags, modules, etc.)
Unfortunately it seems there is no documentation about how this happens. I remember reading (in Slack IIRC) that the nginx in use in this buildpack is built in a Concourse pipeline, but I can't find any official documentation about it, so I can't point our users to something formal.

Would it be possible to include in the documentation:
- where/how is the nginx built
- which configuration is in use during the build process

**Comment by sclevine** [comment]
Our workflow and pipeline are documented:
https://docs.cloudfoundry.org/buildpacks/developing-buildpacks.html
https://docs.cloudfoundry.org/buildpacks/buildpack-ci-index.html

Our entire CI/CD system is open source, and you can deploy it yourself:
https://github.com/cloudfoundry/buildpacks-ci

And the buildpack dependencies (like NGINX) are built from easy-to-read chef recipes:
https://github.com/cloudfoundry/binary-builder/blob/master/recipe/nginx.rb

**Comment by CAFxX** [comment]
@sclevine thanks, putting that in each buildpack docs so that buildpack users that may not be intimately familiar with how these things are done would be a very good start and would cover my request (i.e. "where/how is the nginx built", "which configuration is in use during the build process")

**Comment by sclevine** [comment]
Story is here: https://www.pivotaltracker.com/story/show/153291135
